[package]
name = "dada-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
dada-breakpoint = { path = "../dada-breakpoint" }
dada-db = { path = "../dada-db" }
dada-collections = { path = "../dada-collections" }
dada-ir = { path = "../dada-ir" }
dada-error-format = { path = "../dada-error-format" }
dada-execute = { path = "../dada-execute" }
dada-parse = { path = "../dada-parse" }
dada-lex = { path = "../dada-lex" }
dada-lsp = { path = "../dada-lsp" }
ignore = "0.4.18"
lsp-server = "0.6.0"
lsp-types = "0.93.0"
eyre = "0.6.8"
parking_lot = "0.12.1"
regex = "1.6.0"
serde = "1.0.143"
serde_json = "1.0.83"
similar = "2.2.0"
salsa = { path = "../salsa" }
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.36"
tracing-log = "0.1"
tracing-tree = "0.2.1"
tracing-subscriber = { version = "0.3.15", default-features = false, features = ["fmt", "env-filter", "smallvec", "parking_lot", "ansi"] }
tree-sitter-dada = { path = "../../tree-sitter-dada" }
tree-sitter = "0.20.8"
