[package]
name = "dada-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
dada-breakpoint = { path = "../dada-breakpoint" }
dada-db = { path = "../dada-db" }
dada-collections = { path = "../dada-collections" }
dada-ir = { path = "../dada-ir" }
dada-error-format = { path = "../dada-error-format" }
dada-execute = { path = "../dada-execute" }
dada-parse = { path = "../dada-parse" }
dada-reference-grammar = { path = "../dada-reference-grammar" }
dada-lex = { path = "../dada-lex" }
dada-lsp = { path = "../dada-lsp" }
ignore = "0.4.18"
lsp-server = "0.5.2"
lsp-types = "0.83.1"
eyre = "0.6.7"
parking_lot = "0.11.2"
regex = "1.5.4"
serde = "1.0.131"
serde_json = "1.0.72"
similar = "2.1.0"
salsa = { path = "../salsa" }
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.29"
tracing-log = "0.1"
tracing-tree = "0.2.0"
tracing-subscriber = { version = "0.3.3", default-features = false, features = ["fmt", "env-filter", "smallvec", "parking_lot", "ansi"] }
