// ---------------------------------------------------------
// This file was generated by parol.
// It is not intended for manual editing and changes will be
// lost after next build.
// ---------------------------------------------------------

use id_tree::Tree;

use crate::grammar::Grammar;
use miette::{miette, Result};
use parol_runtime::parser::{ParseTreeStackEntry, ParseTreeType, UserActionsTrait};

///
/// The `GrammarTrait` trait is automatically generated for the
/// given grammar.
/// All functions have default implementations.
///
pub trait GrammarTrait {
    /// Semantic action for production 0:
    ///
    /// Items: ItemsList /* Vec */;
    ///
    fn items(
        &mut self,
        _items_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 1:
    ///
    /// ItemsList: Item ItemsList; // Vec<T>::Push
    ///
    fn items_list_0(
        &mut self,
        _item: &ParseTreeStackEntry,
        _items_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 2:
    ///
    /// ItemsList: ; // Vec<T>::New
    ///
    fn items_list_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 3:
    ///
    /// Item: Class;
    ///
    fn item_0(
        &mut self,
        _class: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 4:
    ///
    /// Item: Function;
    ///
    fn item_1(
        &mut self,
        _function: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 5:
    ///
    /// Class: "class" Identifier FieldList;
    ///
    fn class(
        &mut self,
        _class: &ParseTreeStackEntry,
        _identifier: &ParseTreeStackEntry,
        _field_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 6:
    ///
    /// FieldList: "\(" FieldListSuffix;
    ///
    fn field_list(
        &mut self,
        _l_paren: &ParseTreeStackEntry,
        _field_list_suffix: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 7:
    ///
    /// FieldListSuffix: "\)";
    ///
    fn field_list_suffix_0(
        &mut self,
        _r_paren: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 8:
    ///
    /// FieldListSuffix: Field FieldListList /* Vec */ "\)";
    ///
    fn field_list_suffix_1(
        &mut self,
        _field: &ParseTreeStackEntry,
        _field_list_list: &ParseTreeStackEntry,
        _r_paren: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 9:
    ///
    /// FieldListList: FieldListOpt /* Option */ Field FieldListList; // Vec<T>::Push
    ///
    fn field_list_list_0(
        &mut self,
        _field_list_opt: &ParseTreeStackEntry,
        _field: &ParseTreeStackEntry,
        _field_list_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 10:
    ///
    /// FieldListList: ; // Vec<T>::New
    ///
    fn field_list_list_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 11:
    ///
    /// FieldListOpt: ","; // Option<T>::Some
    ///
    fn field_list_opt_0(
        &mut self,
        _comma: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 12:
    ///
    /// FieldListOpt: ; // Option<T>::None
    ///
    fn field_list_opt_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 13:
    ///
    /// Field: FieldOpt /* Option */ Identifier;
    ///
    fn field(
        &mut self,
        _field_opt: &ParseTreeStackEntry,
        _identifier: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 14:
    ///
    /// FieldOpt: StorageMode; // Option<T>::Some
    ///
    fn field_opt_0(
        &mut self,
        _storage_mode: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 15:
    ///
    /// FieldOpt: ; // Option<T>::None
    ///
    fn field_opt_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 16:
    ///
    /// StorageMode: "atomic";
    ///
    fn storage_mode(
        &mut self,
        _storage_mode: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 17:
    ///
    /// Function: FunctionOpt /* Option */ "fn" Identifier ArgumentList FunctionBody;
    ///
    fn function(
        &mut self,
        _function_opt: &ParseTreeStackEntry,
        _fn: &ParseTreeStackEntry,
        _identifier: &ParseTreeStackEntry,
        _argument_list: &ParseTreeStackEntry,
        _function_body: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 18:
    ///
    /// FunctionOpt: Effect; // Option<T>::Some
    ///
    fn function_opt_0(
        &mut self,
        _effect: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 19:
    ///
    /// FunctionOpt: ; // Option<T>::None
    ///
    fn function_opt_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 20:
    ///
    /// Effect: "async";
    ///
    fn effect(
        &mut self,
        _effect: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 21:
    ///
    /// ArgumentList: "\(" ArgumentListSuffix;
    ///
    fn argument_list(
        &mut self,
        _l_paren: &ParseTreeStackEntry,
        _argument_list_suffix: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 22:
    ///
    /// ArgumentListSuffix: "\)";
    ///
    fn argument_list_suffix_0(
        &mut self,
        _r_paren: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 23:
    ///
    /// ArgumentListSuffix: Identifier ArgumentListList /* Vec */ "\)";
    ///
    fn argument_list_suffix_1(
        &mut self,
        _identifier: &ParseTreeStackEntry,
        _argument_list_list: &ParseTreeStackEntry,
        _r_paren: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 24:
    ///
    /// ArgumentListList: "," Identifier ArgumentListList; // Vec<T>::Push
    ///
    fn argument_list_list_0(
        &mut self,
        _comma: &ParseTreeStackEntry,
        _identifier: &ParseTreeStackEntry,
        _argument_list_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 25:
    ///
    /// ArgumentListList: ; // Vec<T>::New
    ///
    fn argument_list_list_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 26:
    ///
    /// FunctionBody: BlockExpr;
    ///
    fn function_body(
        &mut self,
        _block_expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 27:
    ///
    /// Expr: LocalVariable;
    ///
    fn expr_0(
        &mut self,
        _local_variable: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 28:
    ///
    /// Expr: ReturnWithExpr;
    ///
    fn expr_1(
        &mut self,
        _return_with_expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 29:
    ///
    /// Expr: Expr5;
    ///
    fn expr_2(
        &mut self,
        _expr5: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 30:
    ///
    /// ReturnWithExpr: "return" Expr;
    ///
    fn return_with_expr(
        &mut self,
        _return_without_expr: &ParseTreeStackEntry,
        _expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 31:
    ///
    /// ReturnWithoutExpr: "return";
    ///
    fn return_without_expr(
        &mut self,
        _return_without_expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 32:
    ///
    /// Expr5: Expr4 Expr5List /* Vec */;
    ///
    fn expr5(
        &mut self,
        _expr4: &ParseTreeStackEntry,
        _expr5_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 33:
    ///
    /// Expr5List: Expr5ListGroup Expr4 Expr5List; // Vec<T>::Push
    ///
    fn expr5_list_0(
        &mut self,
        _expr5_list_group: &ParseTreeStackEntry,
        _expr4: &ParseTreeStackEntry,
        _expr5_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 34:
    ///
    /// Expr5ListGroup: "\+=";
    ///
    fn expr5_list_group_0(
        &mut self,
        _plus_equ: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 35:
    ///
    /// Expr5ListGroup: "-=";
    ///
    fn expr5_list_group_1(
        &mut self,
        _minus_equ: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 36:
    ///
    /// Expr5ListGroup: "/=";
    ///
    fn expr5_list_group_2(
        &mut self,
        _slash_equ: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 37:
    ///
    /// Expr5ListGroup: "\*=";
    ///
    fn expr5_list_group_3(
        &mut self,
        _star_equ: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 38:
    ///
    /// Expr5ListGroup: ":=";
    ///
    fn expr5_list_group_4(
        &mut self,
        _colon_equ: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 39:
    ///
    /// Expr5List: ; // Vec<T>::New
    ///
    fn expr5_list_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 40:
    ///
    /// Expr4: Expr3 Expr4List /* Vec */;
    ///
    fn expr4(
        &mut self,
        _expr3: &ParseTreeStackEntry,
        _expr4_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 41:
    ///
    /// Expr4List: Expr4ListGroup Expr3 Expr4List; // Vec<T>::Push
    ///
    fn expr4_list_0(
        &mut self,
        _expr4_list_group: &ParseTreeStackEntry,
        _expr3: &ParseTreeStackEntry,
        _expr4_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 42:
    ///
    /// Expr4ListGroup: "==";
    ///
    fn expr4_list_group_0(
        &mut self,
        _equ_equ: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 43:
    ///
    /// Expr4ListGroup: "<";
    ///
    fn expr4_list_group_1(
        &mut self,
        _l_t: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 44:
    ///
    /// Expr4ListGroup: ">";
    ///
    fn expr4_list_group_2(
        &mut self,
        _g_t: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 45:
    ///
    /// Expr4List: ; // Vec<T>::New
    ///
    fn expr4_list_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 46:
    ///
    /// Expr3: Expr2 Expr3List /* Vec */;
    ///
    fn expr3(
        &mut self,
        _expr2: &ParseTreeStackEntry,
        _expr3_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 47:
    ///
    /// Expr3List: Expr3ListGroup Expr2 Expr3List; // Vec<T>::Push
    ///
    fn expr3_list_0(
        &mut self,
        _expr3_list_group: &ParseTreeStackEntry,
        _expr2: &ParseTreeStackEntry,
        _expr3_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 48:
    ///
    /// Expr3ListGroup: "\+";
    ///
    fn expr3_list_group_0(
        &mut self,
        _plus: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 49:
    ///
    /// Expr3ListGroup: "-";
    ///
    fn expr3_list_group_1(
        &mut self,
        _minus: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 50:
    ///
    /// Expr3List: ; // Vec<T>::New
    ///
    fn expr3_list_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 51:
    ///
    /// Expr2: Expr1 Expr2List /* Vec */;
    ///
    fn expr2(
        &mut self,
        _expr1: &ParseTreeStackEntry,
        _expr2_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 52:
    ///
    /// Expr2List: Expr2ListGroup Expr1 Expr2List; // Vec<T>::Push
    ///
    fn expr2_list_0(
        &mut self,
        _expr2_list_group: &ParseTreeStackEntry,
        _expr1: &ParseTreeStackEntry,
        _expr2_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 53:
    ///
    /// Expr2ListGroup: "/";
    ///
    fn expr2_list_group_0(
        &mut self,
        _slash: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 54:
    ///
    /// Expr2ListGroup: "\*";
    ///
    fn expr2_list_group_1(
        &mut self,
        _star: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 55:
    ///
    /// Expr2List: ; // Vec<T>::New
    ///
    fn expr2_list_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 56:
    ///
    /// Expr1: Expr0 Expr1List /* Vec */;
    ///
    fn expr1(
        &mut self,
        _expr0: &ParseTreeStackEntry,
        _expr1_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 57:
    ///
    /// Expr1List: Expr1ListGroup Expr1List; // Vec<T>::Push
    ///
    fn expr1_list_0(
        &mut self,
        _expr1_list_group: &ParseTreeStackEntry,
        _expr1_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 58:
    ///
    /// Expr1ListGroup: DotExpr;
    ///
    fn expr1_list_group_0(
        &mut self,
        _dot_expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 59:
    ///
    /// Expr1ListGroup: CallArgumentList;
    ///
    fn expr1_list_group_1(
        &mut self,
        _call_argument_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 60:
    ///
    /// Expr1List: ; // Vec<T>::New
    ///
    fn expr1_list_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 61:
    ///
    /// DotExpr: "\." DotSuffix;
    ///
    fn dot_expr(
        &mut self,
        _dot: &ParseTreeStackEntry,
        _dot_suffix: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 62:
    ///
    /// DotSuffix: "await";
    ///
    fn dot_suffix_0(
        &mut self,
        _await: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 63:
    ///
    /// DotSuffix: "share";
    ///
    fn dot_suffix_1(
        &mut self,
        _share: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 64:
    ///
    /// DotSuffix: "give";
    ///
    fn dot_suffix_2(
        &mut self,
        _give: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 65:
    ///
    /// DotSuffix: "lease";
    ///
    fn dot_suffix_3(
        &mut self,
        _lease: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 66:
    ///
    /// DotSuffix: Identifier;
    ///
    fn dot_suffix_4(
        &mut self,
        _identifier: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 67:
    ///
    /// CallArgumentList: "\(" CallArgumentListSuffix;
    ///
    fn call_argument_list(
        &mut self,
        _l_paren: &ParseTreeStackEntry,
        _call_argument_list_suffix: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 68:
    ///
    /// CallArgumentListSuffix: "\)";
    ///
    fn call_argument_list_suffix_0(
        &mut self,
        _r_paren: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 69:
    ///
    /// CallArgumentListSuffix: CallArgument CallArgumentListList /* Vec */ MaybeTrailingComma "\)";
    ///
    fn call_argument_list_suffix_1(
        &mut self,
        _call_argument: &ParseTreeStackEntry,
        _call_argument_list_list: &ParseTreeStackEntry,
        _maybe_trailing_comma: &ParseTreeStackEntry,
        _r_paren: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 70:
    ///
    /// CallArgumentListList: "," CallArgument CallArgumentListList; // Vec<T>::Push
    ///
    fn call_argument_list_list_0(
        &mut self,
        _comma: &ParseTreeStackEntry,
        _call_argument: &ParseTreeStackEntry,
        _call_argument_list_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 71:
    ///
    /// CallArgumentListList: ; // Vec<T>::New
    ///
    fn call_argument_list_list_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 72:
    ///
    /// MaybeTrailingComma: MaybeTrailingCommaOpt /* Option */;
    ///
    fn maybe_trailing_comma(
        &mut self,
        _maybe_trailing_comma_opt: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 73:
    ///
    /// MaybeTrailingCommaOpt: ","; // Option<T>::Some
    ///
    fn maybe_trailing_comma_opt_0(
        &mut self,
        _comma: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 74:
    ///
    /// MaybeTrailingCommaOpt: ; // Option<T>::None
    ///
    fn maybe_trailing_comma_opt_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 75:
    ///
    /// CallArgument: CallArgumentOpt /* Option */ Expr;
    ///
    fn call_argument(
        &mut self,
        _call_argument_opt: &ParseTreeStackEntry,
        _expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 76:
    ///
    /// CallArgumentOpt: Identifier ":"; // Option<T>::Some
    ///
    fn call_argument_opt_0(
        &mut self,
        _identifier: &ParseTreeStackEntry,
        _colon: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 77:
    ///
    /// CallArgumentOpt: ; // Option<T>::None
    ///
    fn call_argument_opt_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 78:
    ///
    /// Expr0: Identifier;
    ///
    fn expr0_0(
        &mut self,
        _identifier: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 79:
    ///
    /// Expr0: BooleanLiteral;
    ///
    fn expr0_1(
        &mut self,
        _boolean_literal: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 80:
    ///
    /// Expr0: FloatLiteral;
    ///
    fn expr0_2(
        &mut self,
        _float_literal: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 81:
    ///
    /// Expr0: IntegerLiteral;
    ///
    fn expr0_3(
        &mut self,
        _integer_literal: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 82:
    ///
    /// Expr0: StringLiteral;
    ///
    fn expr0_4(
        &mut self,
        _string_literal: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 83:
    ///
    /// Expr0: BlockExpr;
    ///
    fn expr0_5(
        &mut self,
        _block_expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 84:
    ///
    /// Expr0: AtomicBlock;
    ///
    fn expr0_6(
        &mut self,
        _atomic_block: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 85:
    ///
    /// Expr0: IfExpr;
    ///
    fn expr0_7(
        &mut self,
        _if_expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 86:
    ///
    /// Expr0: Loop;
    ///
    fn expr0_8(
        &mut self,
        _loop: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 87:
    ///
    /// Expr0: While;
    ///
    fn expr0_9(
        &mut self,
        _while: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 88:
    ///
    /// Expr0: Tuple;
    ///
    fn expr0_10(
        &mut self,
        _tuple: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 89:
    ///
    /// BooleanLiteral: "true";
    ///
    fn boolean_literal_0(
        &mut self,
        _true: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 90:
    ///
    /// BooleanLiteral: "false";
    ///
    fn boolean_literal_1(
        &mut self,
        _false: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 91:
    ///
    /// Identifier: "[a-z|A-Z_][a-z|A-Z|0-9_]*";
    ///
    fn identifier(
        &mut self,
        _identifier: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 92:
    ///
    /// FloatLiteral: "[0-9][0-9_]*\.[0-9][0-9_]*";
    ///
    fn float_literal(
        &mut self,
        _float_literal: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 93:
    ///
    /// IntegerLiteral: "[0-9][0-9_]*";
    ///
    fn integer_literal(
        &mut self,
        _integer_literal: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 94:
    ///
    /// StringLiteral: "\u{0022}(?s:[^\u{0022}]*)\u{0022}";
    ///
    fn string_literal(
        &mut self,
        _string_literal: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 95:
    ///
    /// BlockExpr: "\{" BlockExprList /* Vec */ BlockExprOpt /* Option */ "\}";
    ///
    fn block_expr(
        &mut self,
        _l_brace: &ParseTreeStackEntry,
        _block_expr_list: &ParseTreeStackEntry,
        _block_expr_opt: &ParseTreeStackEntry,
        _r_brace: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 96:
    ///
    /// BlockExprList: Expr BlockExprList; // Vec<T>::Push
    ///
    fn block_expr_list_0(
        &mut self,
        _expr: &ParseTreeStackEntry,
        _block_expr_list: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 97:
    ///
    /// BlockExprList: ; // Vec<T>::New
    ///
    fn block_expr_list_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 98:
    ///
    /// BlockExprOpt: ReturnWithoutExpr; // Option<T>::Some
    ///
    fn block_expr_opt_0(
        &mut self,
        _return_without_expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 99:
    ///
    /// BlockExprOpt: ; // Option<T>::None
    ///
    fn block_expr_opt_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 100:
    ///
    /// AtomicBlock: "atomic" BlockExpr;
    ///
    fn atomic_block(
        &mut self,
        _storage_mode: &ParseTreeStackEntry,
        _block_expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 101:
    ///
    /// IfExpr: "if" Condition BlockExpr IfExprOpt /* Option */;
    ///
    fn if_expr(
        &mut self,
        _if: &ParseTreeStackEntry,
        _condition: &ParseTreeStackEntry,
        _block_expr: &ParseTreeStackEntry,
        _if_expr_opt: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 102:
    ///
    /// IfExprOpt: "else" BlockExpr; // Option<T>::Some
    ///
    fn if_expr_opt_0(
        &mut self,
        _else: &ParseTreeStackEntry,
        _block_expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 103:
    ///
    /// IfExprOpt: ; // Option<T>::None
    ///
    fn if_expr_opt_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 104:
    ///
    /// Condition: Expr;
    ///
    fn condition(
        &mut self,
        _expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 105:
    ///
    /// Loop: "loop" BlockExpr;
    ///
    fn r#loop(
        &mut self,
        _loop: &ParseTreeStackEntry,
        _block_expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 106:
    ///
    /// While: "while" Condition BlockExpr;
    ///
    fn r#while(
        &mut self,
        _while: &ParseTreeStackEntry,
        _condition: &ParseTreeStackEntry,
        _block_expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 107:
    ///
    /// Tuple: "tuple";
    ///
    fn tuple(
        &mut self,
        _tuple: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 108:
    ///
    /// LocalVariable: LocalVariableOpt /* Option */ Identifier "=" Expr;
    ///
    fn local_variable(
        &mut self,
        _local_variable_opt: &ParseTreeStackEntry,
        _identifier: &ParseTreeStackEntry,
        _equ: &ParseTreeStackEntry,
        _expr: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 109:
    ///
    /// LocalVariableOpt: StorageMode; // Option<T>::Some
    ///
    fn local_variable_opt_0(
        &mut self,
        _storage_mode: &ParseTreeStackEntry,
        _parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        Ok(())
    }

    /// Semantic action for production 110:
    ///
    /// LocalVariableOpt: ; // Option<T>::None
    ///
    fn local_variable_opt_1(&mut self, _parse_tree: &Tree<ParseTreeType>) -> Result<()> {
        Ok(())
    }
}

impl UserActionsTrait<'_> for Grammar {
    ///
    /// This function is implemented automatically for the user's item Grammar.
    ///
    fn call_semantic_action_for_production_number(
        &mut self,
        prod_num: usize,
        children: &[ParseTreeStackEntry],
        parse_tree: &Tree<ParseTreeType>,
    ) -> Result<()> {
        match prod_num {
            0 => self.items(&children[0], parse_tree),
            1 => self.items_list_0(&children[0], &children[1], parse_tree),
            2 => self.items_list_1(parse_tree),
            3 => self.item_0(&children[0], parse_tree),
            4 => self.item_1(&children[0], parse_tree),
            5 => self.class(&children[0], &children[1], &children[2], parse_tree),
            6 => self.field_list(&children[0], &children[1], parse_tree),
            7 => self.field_list_suffix_0(&children[0], parse_tree),
            8 => self.field_list_suffix_1(&children[0], &children[1], &children[2], parse_tree),
            9 => self.field_list_list_0(&children[0], &children[1], &children[2], parse_tree),
            10 => self.field_list_list_1(parse_tree),
            11 => self.field_list_opt_0(&children[0], parse_tree),
            12 => self.field_list_opt_1(parse_tree),
            13 => self.field(&children[0], &children[1], parse_tree),
            14 => self.field_opt_0(&children[0], parse_tree),
            15 => self.field_opt_1(parse_tree),
            16 => self.storage_mode(&children[0], parse_tree),
            17 => self.function(
                &children[0],
                &children[1],
                &children[2],
                &children[3],
                &children[4],
                parse_tree,
            ),
            18 => self.function_opt_0(&children[0], parse_tree),
            19 => self.function_opt_1(parse_tree),
            20 => self.effect(&children[0], parse_tree),
            21 => self.argument_list(&children[0], &children[1], parse_tree),
            22 => self.argument_list_suffix_0(&children[0], parse_tree),
            23 => self.argument_list_suffix_1(&children[0], &children[1], &children[2], parse_tree),
            24 => self.argument_list_list_0(&children[0], &children[1], &children[2], parse_tree),
            25 => self.argument_list_list_1(parse_tree),
            26 => self.function_body(&children[0], parse_tree),
            27 => self.expr_0(&children[0], parse_tree),
            28 => self.expr_1(&children[0], parse_tree),
            29 => self.expr_2(&children[0], parse_tree),
            30 => self.return_with_expr(&children[0], &children[1], parse_tree),
            31 => self.return_without_expr(&children[0], parse_tree),
            32 => self.expr5(&children[0], &children[1], parse_tree),
            33 => self.expr5_list_0(&children[0], &children[1], &children[2], parse_tree),
            34 => self.expr5_list_group_0(&children[0], parse_tree),
            35 => self.expr5_list_group_1(&children[0], parse_tree),
            36 => self.expr5_list_group_2(&children[0], parse_tree),
            37 => self.expr5_list_group_3(&children[0], parse_tree),
            38 => self.expr5_list_group_4(&children[0], parse_tree),
            39 => self.expr5_list_1(parse_tree),
            40 => self.expr4(&children[0], &children[1], parse_tree),
            41 => self.expr4_list_0(&children[0], &children[1], &children[2], parse_tree),
            42 => self.expr4_list_group_0(&children[0], parse_tree),
            43 => self.expr4_list_group_1(&children[0], parse_tree),
            44 => self.expr4_list_group_2(&children[0], parse_tree),
            45 => self.expr4_list_1(parse_tree),
            46 => self.expr3(&children[0], &children[1], parse_tree),
            47 => self.expr3_list_0(&children[0], &children[1], &children[2], parse_tree),
            48 => self.expr3_list_group_0(&children[0], parse_tree),
            49 => self.expr3_list_group_1(&children[0], parse_tree),
            50 => self.expr3_list_1(parse_tree),
            51 => self.expr2(&children[0], &children[1], parse_tree),
            52 => self.expr2_list_0(&children[0], &children[1], &children[2], parse_tree),
            53 => self.expr2_list_group_0(&children[0], parse_tree),
            54 => self.expr2_list_group_1(&children[0], parse_tree),
            55 => self.expr2_list_1(parse_tree),
            56 => self.expr1(&children[0], &children[1], parse_tree),
            57 => self.expr1_list_0(&children[0], &children[1], parse_tree),
            58 => self.expr1_list_group_0(&children[0], parse_tree),
            59 => self.expr1_list_group_1(&children[0], parse_tree),
            60 => self.expr1_list_1(parse_tree),
            61 => self.dot_expr(&children[0], &children[1], parse_tree),
            62 => self.dot_suffix_0(&children[0], parse_tree),
            63 => self.dot_suffix_1(&children[0], parse_tree),
            64 => self.dot_suffix_2(&children[0], parse_tree),
            65 => self.dot_suffix_3(&children[0], parse_tree),
            66 => self.dot_suffix_4(&children[0], parse_tree),
            67 => self.call_argument_list(&children[0], &children[1], parse_tree),
            68 => self.call_argument_list_suffix_0(&children[0], parse_tree),
            69 => self.call_argument_list_suffix_1(
                &children[0],
                &children[1],
                &children[2],
                &children[3],
                parse_tree,
            ),
            70 => {
                self.call_argument_list_list_0(&children[0], &children[1], &children[2], parse_tree)
            }
            71 => self.call_argument_list_list_1(parse_tree),
            72 => self.maybe_trailing_comma(&children[0], parse_tree),
            73 => self.maybe_trailing_comma_opt_0(&children[0], parse_tree),
            74 => self.maybe_trailing_comma_opt_1(parse_tree),
            75 => self.call_argument(&children[0], &children[1], parse_tree),
            76 => self.call_argument_opt_0(&children[0], &children[1], parse_tree),
            77 => self.call_argument_opt_1(parse_tree),
            78 => self.expr0_0(&children[0], parse_tree),
            79 => self.expr0_1(&children[0], parse_tree),
            80 => self.expr0_2(&children[0], parse_tree),
            81 => self.expr0_3(&children[0], parse_tree),
            82 => self.expr0_4(&children[0], parse_tree),
            83 => self.expr0_5(&children[0], parse_tree),
            84 => self.expr0_6(&children[0], parse_tree),
            85 => self.expr0_7(&children[0], parse_tree),
            86 => self.expr0_8(&children[0], parse_tree),
            87 => self.expr0_9(&children[0], parse_tree),
            88 => self.expr0_10(&children[0], parse_tree),
            89 => self.boolean_literal_0(&children[0], parse_tree),
            90 => self.boolean_literal_1(&children[0], parse_tree),
            91 => self.identifier(&children[0], parse_tree),
            92 => self.float_literal(&children[0], parse_tree),
            93 => self.integer_literal(&children[0], parse_tree),
            94 => self.string_literal(&children[0], parse_tree),
            95 => self.block_expr(
                &children[0],
                &children[1],
                &children[2],
                &children[3],
                parse_tree,
            ),
            96 => self.block_expr_list_0(&children[0], &children[1], parse_tree),
            97 => self.block_expr_list_1(parse_tree),
            98 => self.block_expr_opt_0(&children[0], parse_tree),
            99 => self.block_expr_opt_1(parse_tree),
            100 => self.atomic_block(&children[0], &children[1], parse_tree),
            101 => self.if_expr(
                &children[0],
                &children[1],
                &children[2],
                &children[3],
                parse_tree,
            ),
            102 => self.if_expr_opt_0(&children[0], &children[1], parse_tree),
            103 => self.if_expr_opt_1(parse_tree),
            104 => self.condition(&children[0], parse_tree),
            105 => self.r#loop(&children[0], &children[1], parse_tree),
            106 => self.r#while(&children[0], &children[1], &children[2], parse_tree),
            107 => self.tuple(&children[0], parse_tree),
            108 => self.local_variable(
                &children[0],
                &children[1],
                &children[2],
                &children[3],
                parse_tree,
            ),
            109 => self.local_variable_opt_0(&children[0], parse_tree),
            110 => self.local_variable_opt_1(parse_tree),
            _ => Err(miette!("Unhandled production number: {}", prod_num)),
        }
    }
}
