// ---------------------------------------------------------
// This file was generated by parol.
// It is not intended for manual editing and changes will be
// lost after next build.
// ---------------------------------------------------------

use id_tree::Tree;
use miette::Result;
use parol_runtime::lexer::{TokenStream, Tokenizer};
#[allow(unused_imports)]
use parol_runtime::parser::{
    DFATransition, LLKParser, LookaheadDFA, ParseTreeType, ParseType, Production, UserActionsTrait,
};
use std::cell::RefCell;
use std::path::Path;

use parol_runtime::lexer::tokenizer::{
    ERROR_TOKEN, NEW_LINE_TOKEN, UNMATCHABLE_TOKEN, WHITESPACE_TOKEN,
};

pub const TERMINALS: &[&str; 38] = &[
    /*  0 */ UNMATCHABLE_TOKEN,
    /*  1 */ UNMATCHABLE_TOKEN,
    /*  2 */ UNMATCHABLE_TOKEN,
    /*  3 */ UNMATCHABLE_TOKEN,
    /*  4 */ UNMATCHABLE_TOKEN,
    /*  5 */ r###"class"###,
    /*  6 */ r###","###,
    /*  7 */ r###"\n"###,
    /*  8 */ r###"\("###,
    /*  9 */ r###"\)"###,
    /* 10 */ r###"atomic"###,
    /* 11 */ r###"fn"###,
    /* 12 */ r###"async"###,
    /* 13 */ r###"(?:\+|-|/|\*|:)="###,
    /* 14 */ r###"==|<|>"###,
    /* 15 */ r###"\+|-"###,
    /* 16 */ r###"/|\*"###,
    /* 17 */ r###"\."###,
    /* 18 */ r###"await"###,
    /* 19 */ r###"share"###,
    /* 20 */ r###"give"###,
    /* 21 */ r###"lease"###,
    /* 22 */ r###":"###,
    /* 23 */ r###"true|false"###,
    /* 24 */ r###"[a-z|A-Z_][a-z|A-Z|0-9_]*"###,
    /* 25 */ r###"[0-9][0-9_]*\.[0-9][0-9_]*"###,
    /* 26 */ r###"[0-9][0-9_]*"###,
    /* 27 */ r###"\u{0022}(?s:[^\u{0022}]*)\u{0022}"###,
    /* 28 */ r###"return"###,
    /* 29 */ r###"\{"###,
    /* 30 */ r###"\}"###,
    /* 31 */ r###"if"###,
    /* 32 */ r###"else"###,
    /* 33 */ r###"loop"###,
    /* 34 */ r###"while"###,
    /* 35 */ r###"tuple"###,
    /* 36 */ r###"="###,
    /* 37 */ ERROR_TOKEN,
];

pub const TERMINAL_NAMES: &[&str; 38] = &[
    /*  0 */ "EndOfInput",
    /*  1 */ "Newline",
    /*  2 */ "Whitespace",
    /*  3 */ "LineComment",
    /*  4 */ "BlockComment",
    /*  5 */ "Class",
    /*  6 */ "Comma",
    /*  7 */ "N",
    /*  8 */ "LParen",
    /*  9 */ "RParen",
    /* 10 */ "StorageMode",
    /* 11 */ "Fn",
    /* 12 */ "Effect",
    /* 13 */ "LParenQuestColonPlusOrMinusOrSlashOrStarOrColonRParenEqu",
    /* 14 */ "EquEquOrLTOrGT",
    /* 15 */ "PlusOrMinus",
    /* 16 */ "SlashOrStar",
    /* 17 */ "Dot",
    /* 18 */ "Await",
    /* 19 */ "Share",
    /* 20 */ "Give",
    /* 21 */ "Lease",
    /* 22 */ "Colon",
    /* 23 */ "BooleanLiteral",
    /* 24 */ "Identifier",
    /* 25 */ "FloatLiteral",
    /* 26 */ "IntegerLiteral",
    /* 27 */ "StringLiteral",
    /* 28 */ "Return",
    /* 29 */ "LBrace",
    /* 30 */ "RBrace",
    /* 31 */ "If",
    /* 32 */ "Else",
    /* 33 */ "Loop",
    /* 34 */ "While",
    /* 35 */ "Tuple",
    /* 36 */ "Equ",
    /* 37 */ "Error",
];

/* SCANNER_0: "INITIAL" */
const SCANNER_0: (&[&str; 5], &[usize; 32]) = (
    &[
        /*  0 */ UNMATCHABLE_TOKEN,
        /*  1 */ NEW_LINE_TOKEN,
        /*  2 */ WHITESPACE_TOKEN,
        /*  3 */ r###"(#.*(\r\n|\r|\n|$))"###,
        /*  4 */ UNMATCHABLE_TOKEN,
    ],
    &[
        5,  /* Class */
        6,  /* Comma */
        7,  /* N */
        8,  /* LParen */
        9,  /* RParen */
        10, /* StorageMode */
        11, /* Fn */
        12, /* Effect */
        13, /* LParenQuestColonPlusOrMinusOrSlashOrStarOrColonRParenEqu */
        14, /* EquEquOrLTOrGT */
        15, /* PlusOrMinus */
        16, /* SlashOrStar */
        17, /* Dot */
        18, /* Await */
        19, /* Share */
        20, /* Give */
        21, /* Lease */
        22, /* Colon */
        23, /* BooleanLiteral */
        24, /* Identifier */
        25, /* FloatLiteral */
        26, /* IntegerLiteral */
        27, /* StringLiteral */
        28, /* Return */
        29, /* LBrace */
        30, /* RBrace */
        31, /* If */
        32, /* Else */
        33, /* Loop */
        34, /* While */
        35, /* Tuple */
        36, /* Equ */
    ],
);

const MAX_K: usize = 2;

pub const NON_TERMINALS: &[&str; 60] = &[
    /*  0 */ "ArgumentList",
    /*  1 */ "ArgumentListList",
    /*  2 */ "ArgumentListSuffix",
    /*  3 */ "AtomicBlock",
    /*  4 */ "BlockExpr",
    /*  5 */ "BlockExprList",
    /*  6 */ "BlockExprOpt",
    /*  7 */ "BooleanLiteral",
    /*  8 */ "CallArgument",
    /*  9 */ "CallArgumentList",
    /* 10 */ "CallArgumentListList",
    /* 11 */ "CallArgumentListSuffix",
    /* 12 */ "CallArgumentOpt",
    /* 13 */ "Class",
    /* 14 */ "Condition",
    /* 15 */ "DotExpr",
    /* 16 */ "DotSuffix",
    /* 17 */ "Effect",
    /* 18 */ "Expr",
    /* 19 */ "Expr0",
    /* 20 */ "Expr1",
    /* 21 */ "Expr1List",
    /* 22 */ "Expr1ListGroup",
    /* 23 */ "Expr2",
    /* 24 */ "Expr2List",
    /* 25 */ "Expr3",
    /* 26 */ "Expr3List",
    /* 27 */ "Expr4",
    /* 28 */ "Expr4List",
    /* 29 */ "Expr5",
    /* 30 */ "Expr5List",
    /* 31 */ "Field",
    /* 32 */ "FieldList",
    /* 33 */ "FieldListList",
    /* 34 */ "FieldListSuffix",
    /* 35 */ "FieldOpt",
    /* 36 */ "FloatLiteral",
    /* 37 */ "Function",
    /* 38 */ "FunctionBody",
    /* 39 */ "FunctionOpt",
    /* 40 */ "Identifier",
    /* 41 */ "IfExpr",
    /* 42 */ "IfExprOpt",
    /* 43 */ "IntegerLiteral",
    /* 44 */ "Item",
    /* 45 */ "Items",
    /* 46 */ "ItemsList",
    /* 47 */ "LocalVariable",
    /* 48 */ "LocalVariableOpt",
    /* 49 */ "Loop",
    /* 50 */ "MaybeTrailingComma",
    /* 51 */ "MaybeTrailingCommaOpt",
    /* 52 */ "ReturnExpr",
    /* 53 */ "ReturnExprOpt",
    /* 54 */ "Sep",
    /* 55 */ "SepList",
    /* 56 */ "StorageMode",
    /* 57 */ "StringLiteral",
    /* 58 */ "Tuple",
    /* 59 */ "While",
];

pub const LOOKAHEAD_AUTOMATA: &[LookaheadDFA; 60] = &[
    /* 0 - "ArgumentList" */
    LookaheadDFA {
        states: &[Some(26)],
        transitions: &[],
        k: 0,
    },
    /* 1 - "ArgumentListList" */
    LookaheadDFA {
        states: &[None, None, Some(29), None, None, Some(30)],
        transitions: &[
            DFATransition(0, 6, 1),
            DFATransition(0, 7, 3),
            DFATransition(0, 9, 4),
            DFATransition(1, 9, 5),
            DFATransition(1, 24, 2),
            DFATransition(3, 7, 2),
            DFATransition(3, 24, 2),
            DFATransition(4, 29, 5),
        ],
        k: 2,
    },
    /* 2 - "ArgumentListSuffix" */
    LookaheadDFA {
        states: &[None, Some(27), Some(28)],
        transitions: &[DFATransition(0, 9, 1), DFATransition(0, 24, 2)],
        k: 1,
    },
    /* 3 - "AtomicBlock" */
    LookaheadDFA {
        states: &[Some(89)],
        transitions: &[],
        k: 0,
    },
    /* 4 - "BlockExpr" */
    LookaheadDFA {
        states: &[Some(84)],
        transitions: &[],
        k: 0,
    },
    /* 5 - "BlockExprList" */
    LookaheadDFA {
        states: &[None, Some(85), Some(86)],
        transitions: &[
            DFATransition(0, 10, 1),
            DFATransition(0, 23, 1),
            DFATransition(0, 24, 1),
            DFATransition(0, 25, 1),
            DFATransition(0, 26, 1),
            DFATransition(0, 27, 1),
            DFATransition(0, 28, 2),
            DFATransition(0, 29, 1),
            DFATransition(0, 30, 2),
            DFATransition(0, 31, 1),
            DFATransition(0, 33, 1),
            DFATransition(0, 34, 1),
            DFATransition(0, 35, 1),
        ],
        k: 1,
    },
    /* 6 - "BlockExprOpt" */
    LookaheadDFA {
        states: &[None, Some(87), Some(88)],
        transitions: &[DFATransition(0, 28, 1), DFATransition(0, 30, 2)],
        k: 1,
    },
    /* 7 - "BooleanLiteral" */
    LookaheadDFA {
        states: &[Some(76)],
        transitions: &[],
        k: 0,
    },
    /* 8 - "CallArgument" */
    LookaheadDFA {
        states: &[Some(62)],
        transitions: &[],
        k: 0,
    },
    /* 9 - "CallArgumentList" */
    LookaheadDFA {
        states: &[Some(57)],
        transitions: &[],
        k: 0,
    },
    /* 10 - "CallArgumentListList" */
    LookaheadDFA {
        states: &[None, None, Some(60), None, None, Some(61)],
        transitions: &[
            DFATransition(0, 6, 1),
            DFATransition(0, 7, 3),
            DFATransition(0, 9, 4),
            DFATransition(1, 9, 5),
            DFATransition(1, 10, 2),
            DFATransition(1, 23, 2),
            DFATransition(1, 24, 2),
            DFATransition(1, 25, 2),
            DFATransition(1, 26, 2),
            DFATransition(1, 27, 2),
            DFATransition(1, 29, 2),
            DFATransition(1, 31, 2),
            DFATransition(1, 33, 2),
            DFATransition(1, 34, 2),
            DFATransition(1, 35, 2),
            DFATransition(3, 7, 2),
            DFATransition(3, 10, 2),
            DFATransition(3, 23, 2),
            DFATransition(3, 24, 2),
            DFATransition(3, 25, 2),
            DFATransition(3, 26, 2),
            DFATransition(3, 27, 2),
            DFATransition(3, 29, 2),
            DFATransition(3, 31, 2),
            DFATransition(3, 33, 2),
            DFATransition(3, 34, 2),
            DFATransition(3, 35, 2),
            DFATransition(4, 6, 5),
            DFATransition(4, 7, 5),
            DFATransition(4, 8, 5),
            DFATransition(4, 9, 5),
            DFATransition(4, 10, 5),
            DFATransition(4, 13, 5),
            DFATransition(4, 14, 5),
            DFATransition(4, 15, 5),
            DFATransition(4, 16, 5),
            DFATransition(4, 17, 5),
            DFATransition(4, 23, 5),
            DFATransition(4, 24, 5),
            DFATransition(4, 25, 5),
            DFATransition(4, 26, 5),
            DFATransition(4, 27, 5),
            DFATransition(4, 28, 5),
            DFATransition(4, 29, 5),
            DFATransition(4, 30, 5),
            DFATransition(4, 31, 5),
            DFATransition(4, 33, 5),
            DFATransition(4, 34, 5),
            DFATransition(4, 35, 5),
        ],
        k: 2,
    },
    /* 11 - "CallArgumentListSuffix" */
    LookaheadDFA {
        states: &[None, Some(58), Some(59)],
        transitions: &[
            DFATransition(0, 9, 1),
            DFATransition(0, 10, 2),
            DFATransition(0, 23, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
            DFATransition(0, 26, 2),
            DFATransition(0, 27, 2),
            DFATransition(0, 29, 2),
            DFATransition(0, 31, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
        ],
        k: 1,
    },
    /* 12 - "CallArgumentOpt" */
    LookaheadDFA {
        states: &[
            None,
            None,
            Some(63),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(64),
        ],
        transitions: &[
            DFATransition(0, 10, 3),
            DFATransition(0, 23, 4),
            DFATransition(0, 24, 1),
            DFATransition(0, 25, 5),
            DFATransition(0, 26, 6),
            DFATransition(0, 27, 7),
            DFATransition(0, 29, 8),
            DFATransition(0, 31, 9),
            DFATransition(0, 33, 10),
            DFATransition(0, 34, 11),
            DFATransition(0, 35, 12),
            DFATransition(1, 6, 13),
            DFATransition(1, 7, 13),
            DFATransition(1, 8, 13),
            DFATransition(1, 9, 13),
            DFATransition(1, 13, 13),
            DFATransition(1, 14, 13),
            DFATransition(1, 15, 13),
            DFATransition(1, 16, 13),
            DFATransition(1, 17, 13),
            DFATransition(1, 22, 2),
            DFATransition(1, 36, 13),
            DFATransition(3, 24, 13),
            DFATransition(3, 29, 13),
            DFATransition(4, 6, 13),
            DFATransition(4, 7, 13),
            DFATransition(4, 8, 13),
            DFATransition(4, 9, 13),
            DFATransition(4, 13, 13),
            DFATransition(4, 14, 13),
            DFATransition(4, 15, 13),
            DFATransition(4, 16, 13),
            DFATransition(4, 17, 13),
            DFATransition(5, 6, 13),
            DFATransition(5, 7, 13),
            DFATransition(5, 8, 13),
            DFATransition(5, 9, 13),
            DFATransition(5, 13, 13),
            DFATransition(5, 14, 13),
            DFATransition(5, 15, 13),
            DFATransition(5, 16, 13),
            DFATransition(5, 17, 13),
            DFATransition(6, 6, 13),
            DFATransition(6, 7, 13),
            DFATransition(6, 8, 13),
            DFATransition(6, 9, 13),
            DFATransition(6, 13, 13),
            DFATransition(6, 14, 13),
            DFATransition(6, 15, 13),
            DFATransition(6, 16, 13),
            DFATransition(6, 17, 13),
            DFATransition(7, 6, 13),
            DFATransition(7, 7, 13),
            DFATransition(7, 8, 13),
            DFATransition(7, 9, 13),
            DFATransition(7, 13, 13),
            DFATransition(7, 14, 13),
            DFATransition(7, 15, 13),
            DFATransition(7, 16, 13),
            DFATransition(7, 17, 13),
            DFATransition(8, 10, 13),
            DFATransition(8, 23, 13),
            DFATransition(8, 24, 13),
            DFATransition(8, 25, 13),
            DFATransition(8, 26, 13),
            DFATransition(8, 27, 13),
            DFATransition(8, 28, 13),
            DFATransition(8, 29, 13),
            DFATransition(8, 30, 13),
            DFATransition(8, 31, 13),
            DFATransition(8, 33, 13),
            DFATransition(8, 34, 13),
            DFATransition(8, 35, 13),
            DFATransition(9, 10, 13),
            DFATransition(9, 23, 13),
            DFATransition(9, 24, 13),
            DFATransition(9, 25, 13),
            DFATransition(9, 26, 13),
            DFATransition(9, 27, 13),
            DFATransition(9, 29, 13),
            DFATransition(9, 31, 13),
            DFATransition(9, 33, 13),
            DFATransition(9, 34, 13),
            DFATransition(9, 35, 13),
            DFATransition(10, 29, 13),
            DFATransition(11, 10, 13),
            DFATransition(11, 23, 13),
            DFATransition(11, 24, 13),
            DFATransition(11, 25, 13),
            DFATransition(11, 26, 13),
            DFATransition(11, 27, 13),
            DFATransition(11, 29, 13),
            DFATransition(11, 31, 13),
            DFATransition(11, 33, 13),
            DFATransition(11, 34, 13),
            DFATransition(11, 35, 13),
            DFATransition(12, 6, 13),
            DFATransition(12, 7, 13),
            DFATransition(12, 8, 13),
            DFATransition(12, 9, 13),
            DFATransition(12, 13, 13),
            DFATransition(12, 14, 13),
            DFATransition(12, 15, 13),
            DFATransition(12, 16, 13),
            DFATransition(12, 17, 13),
        ],
        k: 2,
    },
    /* 13 - "Class" */
    LookaheadDFA {
        states: &[Some(5)],
        transitions: &[],
        k: 0,
    },
    /* 14 - "Condition" */
    LookaheadDFA {
        states: &[Some(93)],
        transitions: &[],
        k: 0,
    },
    /* 15 - "DotExpr" */
    LookaheadDFA {
        states: &[Some(51)],
        transitions: &[],
        k: 0,
    },
    /* 16 - "DotSuffix" */
    LookaheadDFA {
        states: &[None, Some(52), Some(53), Some(54), Some(55), Some(56)],
        transitions: &[
            DFATransition(0, 18, 1),
            DFATransition(0, 19, 2),
            DFATransition(0, 20, 3),
            DFATransition(0, 21, 4),
            DFATransition(0, 24, 5),
        ],
        k: 1,
    },
    /* 17 - "Effect" */
    LookaheadDFA {
        states: &[Some(25)],
        transitions: &[],
        k: 0,
    },
    /* 18 - "Expr" */
    LookaheadDFA {
        states: &[
            None,
            None,
            Some(32),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(33),
        ],
        transitions: &[
            DFATransition(0, 10, 1),
            DFATransition(0, 23, 4),
            DFATransition(0, 24, 3),
            DFATransition(0, 25, 5),
            DFATransition(0, 26, 6),
            DFATransition(0, 27, 7),
            DFATransition(0, 29, 8),
            DFATransition(0, 31, 9),
            DFATransition(0, 33, 10),
            DFATransition(0, 34, 11),
            DFATransition(0, 35, 12),
            DFATransition(1, 24, 2),
            DFATransition(1, 29, 13),
            DFATransition(3, 6, 13),
            DFATransition(3, 7, 13),
            DFATransition(3, 8, 13),
            DFATransition(3, 9, 13),
            DFATransition(3, 10, 13),
            DFATransition(3, 13, 13),
            DFATransition(3, 14, 13),
            DFATransition(3, 15, 13),
            DFATransition(3, 16, 13),
            DFATransition(3, 17, 13),
            DFATransition(3, 23, 13),
            DFATransition(3, 24, 13),
            DFATransition(3, 25, 13),
            DFATransition(3, 26, 13),
            DFATransition(3, 27, 13),
            DFATransition(3, 28, 13),
            DFATransition(3, 29, 13),
            DFATransition(3, 30, 13),
            DFATransition(3, 31, 13),
            DFATransition(3, 33, 13),
            DFATransition(3, 34, 13),
            DFATransition(3, 35, 13),
            DFATransition(3, 36, 2),
            DFATransition(4, 6, 13),
            DFATransition(4, 7, 13),
            DFATransition(4, 8, 13),
            DFATransition(4, 9, 13),
            DFATransition(4, 10, 13),
            DFATransition(4, 13, 13),
            DFATransition(4, 14, 13),
            DFATransition(4, 15, 13),
            DFATransition(4, 16, 13),
            DFATransition(4, 17, 13),
            DFATransition(4, 23, 13),
            DFATransition(4, 24, 13),
            DFATransition(4, 25, 13),
            DFATransition(4, 26, 13),
            DFATransition(4, 27, 13),
            DFATransition(4, 28, 13),
            DFATransition(4, 29, 13),
            DFATransition(4, 30, 13),
            DFATransition(4, 31, 13),
            DFATransition(4, 33, 13),
            DFATransition(4, 34, 13),
            DFATransition(4, 35, 13),
            DFATransition(5, 6, 13),
            DFATransition(5, 7, 13),
            DFATransition(5, 8, 13),
            DFATransition(5, 9, 13),
            DFATransition(5, 10, 13),
            DFATransition(5, 13, 13),
            DFATransition(5, 14, 13),
            DFATransition(5, 15, 13),
            DFATransition(5, 16, 13),
            DFATransition(5, 17, 13),
            DFATransition(5, 23, 13),
            DFATransition(5, 24, 13),
            DFATransition(5, 25, 13),
            DFATransition(5, 26, 13),
            DFATransition(5, 27, 13),
            DFATransition(5, 28, 13),
            DFATransition(5, 29, 13),
            DFATransition(5, 30, 13),
            DFATransition(5, 31, 13),
            DFATransition(5, 33, 13),
            DFATransition(5, 34, 13),
            DFATransition(5, 35, 13),
            DFATransition(6, 6, 13),
            DFATransition(6, 7, 13),
            DFATransition(6, 8, 13),
            DFATransition(6, 9, 13),
            DFATransition(6, 10, 13),
            DFATransition(6, 13, 13),
            DFATransition(6, 14, 13),
            DFATransition(6, 15, 13),
            DFATransition(6, 16, 13),
            DFATransition(6, 17, 13),
            DFATransition(6, 23, 13),
            DFATransition(6, 24, 13),
            DFATransition(6, 25, 13),
            DFATransition(6, 26, 13),
            DFATransition(6, 27, 13),
            DFATransition(6, 28, 13),
            DFATransition(6, 29, 13),
            DFATransition(6, 30, 13),
            DFATransition(6, 31, 13),
            DFATransition(6, 33, 13),
            DFATransition(6, 34, 13),
            DFATransition(6, 35, 13),
            DFATransition(7, 6, 13),
            DFATransition(7, 7, 13),
            DFATransition(7, 8, 13),
            DFATransition(7, 9, 13),
            DFATransition(7, 10, 13),
            DFATransition(7, 13, 13),
            DFATransition(7, 14, 13),
            DFATransition(7, 15, 13),
            DFATransition(7, 16, 13),
            DFATransition(7, 17, 13),
            DFATransition(7, 23, 13),
            DFATransition(7, 24, 13),
            DFATransition(7, 25, 13),
            DFATransition(7, 26, 13),
            DFATransition(7, 27, 13),
            DFATransition(7, 28, 13),
            DFATransition(7, 29, 13),
            DFATransition(7, 30, 13),
            DFATransition(7, 31, 13),
            DFATransition(7, 33, 13),
            DFATransition(7, 34, 13),
            DFATransition(7, 35, 13),
            DFATransition(8, 10, 13),
            DFATransition(8, 23, 13),
            DFATransition(8, 24, 13),
            DFATransition(8, 25, 13),
            DFATransition(8, 26, 13),
            DFATransition(8, 27, 13),
            DFATransition(8, 28, 13),
            DFATransition(8, 29, 13),
            DFATransition(8, 30, 13),
            DFATransition(8, 31, 13),
            DFATransition(8, 33, 13),
            DFATransition(8, 34, 13),
            DFATransition(8, 35, 13),
            DFATransition(9, 10, 13),
            DFATransition(9, 23, 13),
            DFATransition(9, 24, 13),
            DFATransition(9, 25, 13),
            DFATransition(9, 26, 13),
            DFATransition(9, 27, 13),
            DFATransition(9, 29, 13),
            DFATransition(9, 31, 13),
            DFATransition(9, 33, 13),
            DFATransition(9, 34, 13),
            DFATransition(9, 35, 13),
            DFATransition(10, 29, 13),
            DFATransition(11, 10, 13),
            DFATransition(11, 23, 13),
            DFATransition(11, 24, 13),
            DFATransition(11, 25, 13),
            DFATransition(11, 26, 13),
            DFATransition(11, 27, 13),
            DFATransition(11, 29, 13),
            DFATransition(11, 31, 13),
            DFATransition(11, 33, 13),
            DFATransition(11, 34, 13),
            DFATransition(11, 35, 13),
            DFATransition(12, 6, 13),
            DFATransition(12, 7, 13),
            DFATransition(12, 8, 13),
            DFATransition(12, 9, 13),
            DFATransition(12, 10, 13),
            DFATransition(12, 13, 13),
            DFATransition(12, 14, 13),
            DFATransition(12, 15, 13),
            DFATransition(12, 16, 13),
            DFATransition(12, 17, 13),
            DFATransition(12, 23, 13),
            DFATransition(12, 24, 13),
            DFATransition(12, 25, 13),
            DFATransition(12, 26, 13),
            DFATransition(12, 27, 13),
            DFATransition(12, 28, 13),
            DFATransition(12, 29, 13),
            DFATransition(12, 30, 13),
            DFATransition(12, 31, 13),
            DFATransition(12, 33, 13),
            DFATransition(12, 34, 13),
            DFATransition(12, 35, 13),
        ],
        k: 2,
    },
    /* 19 - "Expr0" */
    LookaheadDFA {
        states: &[
            None,
            Some(65),
            Some(66),
            Some(67),
            Some(68),
            Some(69),
            Some(70),
            Some(71),
            Some(72),
            Some(73),
            Some(74),
            Some(75),
        ],
        transitions: &[
            DFATransition(0, 10, 7),
            DFATransition(0, 23, 2),
            DFATransition(0, 24, 1),
            DFATransition(0, 25, 3),
            DFATransition(0, 26, 4),
            DFATransition(0, 27, 5),
            DFATransition(0, 29, 6),
            DFATransition(0, 31, 8),
            DFATransition(0, 33, 9),
            DFATransition(0, 34, 10),
            DFATransition(0, 35, 11),
        ],
        k: 1,
    },
    /* 20 - "Expr1" */
    LookaheadDFA {
        states: &[Some(46)],
        transitions: &[],
        k: 0,
    },
    /* 21 - "Expr1List" */
    LookaheadDFA {
        states: &[None, Some(47), Some(50)],
        transitions: &[
            DFATransition(0, 6, 2),
            DFATransition(0, 7, 2),
            DFATransition(0, 8, 1),
            DFATransition(0, 9, 2),
            DFATransition(0, 10, 2),
            DFATransition(0, 13, 2),
            DFATransition(0, 14, 2),
            DFATransition(0, 15, 2),
            DFATransition(0, 16, 2),
            DFATransition(0, 17, 1),
            DFATransition(0, 23, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
            DFATransition(0, 26, 2),
            DFATransition(0, 27, 2),
            DFATransition(0, 28, 2),
            DFATransition(0, 29, 2),
            DFATransition(0, 30, 2),
            DFATransition(0, 31, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
        ],
        k: 1,
    },
    /* 22 - "Expr1ListGroup" */
    LookaheadDFA {
        states: &[None, Some(48), Some(49)],
        transitions: &[DFATransition(0, 8, 2), DFATransition(0, 17, 1)],
        k: 1,
    },
    /* 23 - "Expr2" */
    LookaheadDFA {
        states: &[Some(43)],
        transitions: &[],
        k: 0,
    },
    /* 24 - "Expr2List" */
    LookaheadDFA {
        states: &[None, Some(44), Some(45)],
        transitions: &[
            DFATransition(0, 6, 2),
            DFATransition(0, 7, 2),
            DFATransition(0, 9, 2),
            DFATransition(0, 10, 2),
            DFATransition(0, 13, 2),
            DFATransition(0, 14, 2),
            DFATransition(0, 15, 2),
            DFATransition(0, 16, 1),
            DFATransition(0, 23, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
            DFATransition(0, 26, 2),
            DFATransition(0, 27, 2),
            DFATransition(0, 28, 2),
            DFATransition(0, 29, 2),
            DFATransition(0, 30, 2),
            DFATransition(0, 31, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
        ],
        k: 1,
    },
    /* 25 - "Expr3" */
    LookaheadDFA {
        states: &[Some(40)],
        transitions: &[],
        k: 0,
    },
    /* 26 - "Expr3List" */
    LookaheadDFA {
        states: &[None, Some(41), Some(42)],
        transitions: &[
            DFATransition(0, 6, 2),
            DFATransition(0, 7, 2),
            DFATransition(0, 9, 2),
            DFATransition(0, 10, 2),
            DFATransition(0, 13, 2),
            DFATransition(0, 14, 2),
            DFATransition(0, 15, 1),
            DFATransition(0, 23, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
            DFATransition(0, 26, 2),
            DFATransition(0, 27, 2),
            DFATransition(0, 28, 2),
            DFATransition(0, 29, 2),
            DFATransition(0, 30, 2),
            DFATransition(0, 31, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
        ],
        k: 1,
    },
    /* 27 - "Expr4" */
    LookaheadDFA {
        states: &[Some(37)],
        transitions: &[],
        k: 0,
    },
    /* 28 - "Expr4List" */
    LookaheadDFA {
        states: &[None, Some(38), Some(39)],
        transitions: &[
            DFATransition(0, 6, 2),
            DFATransition(0, 7, 2),
            DFATransition(0, 9, 2),
            DFATransition(0, 10, 2),
            DFATransition(0, 13, 2),
            DFATransition(0, 14, 1),
            DFATransition(0, 23, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
            DFATransition(0, 26, 2),
            DFATransition(0, 27, 2),
            DFATransition(0, 28, 2),
            DFATransition(0, 29, 2),
            DFATransition(0, 30, 2),
            DFATransition(0, 31, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
        ],
        k: 1,
    },
    /* 29 - "Expr5" */
    LookaheadDFA {
        states: &[Some(34)],
        transitions: &[],
        k: 0,
    },
    /* 30 - "Expr5List" */
    LookaheadDFA {
        states: &[None, Some(35), Some(36)],
        transitions: &[
            DFATransition(0, 6, 2),
            DFATransition(0, 7, 2),
            DFATransition(0, 9, 2),
            DFATransition(0, 10, 2),
            DFATransition(0, 13, 1),
            DFATransition(0, 23, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
            DFATransition(0, 26, 2),
            DFATransition(0, 27, 2),
            DFATransition(0, 28, 2),
            DFATransition(0, 29, 2),
            DFATransition(0, 30, 2),
            DFATransition(0, 31, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
        ],
        k: 1,
    },
    /* 31 - "Field" */
    LookaheadDFA {
        states: &[Some(18)],
        transitions: &[],
        k: 0,
    },
    /* 32 - "FieldList" */
    LookaheadDFA {
        states: &[Some(13)],
        transitions: &[],
        k: 0,
    },
    /* 33 - "FieldListList" */
    LookaheadDFA {
        states: &[None, None, Some(16), None, None, Some(17)],
        transitions: &[
            DFATransition(0, 6, 1),
            DFATransition(0, 7, 3),
            DFATransition(0, 9, 4),
            DFATransition(1, 9, 5),
            DFATransition(1, 10, 2),
            DFATransition(1, 24, 2),
            DFATransition(3, 7, 2),
            DFATransition(3, 10, 2),
            DFATransition(3, 24, 2),
            DFATransition(4, 0, 5),
            DFATransition(4, 5, 5),
            DFATransition(4, 11, 5),
            DFATransition(4, 12, 5),
        ],
        k: 2,
    },
    /* 34 - "FieldListSuffix" */
    LookaheadDFA {
        states: &[None, Some(14), Some(15)],
        transitions: &[
            DFATransition(0, 9, 1),
            DFATransition(0, 10, 2),
            DFATransition(0, 24, 2),
        ],
        k: 1,
    },
    /* 35 - "FieldOpt" */
    LookaheadDFA {
        states: &[None, Some(19), Some(20)],
        transitions: &[DFATransition(0, 10, 1), DFATransition(0, 24, 2)],
        k: 1,
    },
    /* 36 - "FloatLiteral" */
    LookaheadDFA {
        states: &[Some(78)],
        transitions: &[],
        k: 0,
    },
    /* 37 - "Function" */
    LookaheadDFA {
        states: &[Some(22)],
        transitions: &[],
        k: 0,
    },
    /* 38 - "FunctionBody" */
    LookaheadDFA {
        states: &[Some(31)],
        transitions: &[],
        k: 0,
    },
    /* 39 - "FunctionOpt" */
    LookaheadDFA {
        states: &[None, Some(23), Some(24)],
        transitions: &[DFATransition(0, 11, 2), DFATransition(0, 12, 1)],
        k: 1,
    },
    /* 40 - "Identifier" */
    LookaheadDFA {
        states: &[Some(77)],
        transitions: &[],
        k: 0,
    },
    /* 41 - "IfExpr" */
    LookaheadDFA {
        states: &[Some(90)],
        transitions: &[],
        k: 0,
    },
    /* 42 - "IfExprOpt" */
    LookaheadDFA {
        states: &[None, Some(91), Some(92)],
        transitions: &[
            DFATransition(0, 6, 2),
            DFATransition(0, 7, 2),
            DFATransition(0, 8, 2),
            DFATransition(0, 9, 2),
            DFATransition(0, 10, 2),
            DFATransition(0, 13, 2),
            DFATransition(0, 14, 2),
            DFATransition(0, 15, 2),
            DFATransition(0, 16, 2),
            DFATransition(0, 17, 2),
            DFATransition(0, 23, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
            DFATransition(0, 26, 2),
            DFATransition(0, 27, 2),
            DFATransition(0, 28, 2),
            DFATransition(0, 29, 2),
            DFATransition(0, 30, 2),
            DFATransition(0, 31, 2),
            DFATransition(0, 32, 1),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
        ],
        k: 1,
    },
    /* 43 - "IntegerLiteral" */
    LookaheadDFA {
        states: &[Some(79)],
        transitions: &[],
        k: 0,
    },
    /* 44 - "Item" */
    LookaheadDFA {
        states: &[None, Some(3), Some(4)],
        transitions: &[
            DFATransition(0, 5, 1),
            DFATransition(0, 11, 2),
            DFATransition(0, 12, 2),
        ],
        k: 1,
    },
    /* 45 - "Items" */
    LookaheadDFA {
        states: &[Some(0)],
        transitions: &[],
        k: 0,
    },
    /* 46 - "ItemsList" */
    LookaheadDFA {
        states: &[None, Some(1), Some(2)],
        transitions: &[
            DFATransition(0, 0, 2),
            DFATransition(0, 5, 1),
            DFATransition(0, 11, 1),
            DFATransition(0, 12, 1),
        ],
        k: 1,
    },
    /* 47 - "LocalVariable" */
    LookaheadDFA {
        states: &[Some(97)],
        transitions: &[],
        k: 0,
    },
    /* 48 - "LocalVariableOpt" */
    LookaheadDFA {
        states: &[None, Some(98), Some(99)],
        transitions: &[DFATransition(0, 10, 1), DFATransition(0, 24, 2)],
        k: 1,
    },
    /* 49 - "Loop" */
    LookaheadDFA {
        states: &[Some(94)],
        transitions: &[],
        k: 0,
    },
    /* 50 - "MaybeTrailingComma" */
    LookaheadDFA {
        states: &[Some(10)],
        transitions: &[],
        k: 0,
    },
    /* 51 - "MaybeTrailingCommaOpt" */
    LookaheadDFA {
        states: &[None, Some(11), Some(12)],
        transitions: &[DFATransition(0, 6, 1), DFATransition(0, 9, 2)],
        k: 1,
    },
    /* 52 - "ReturnExpr" */
    LookaheadDFA {
        states: &[Some(81)],
        transitions: &[],
        k: 0,
    },
    /* 53 - "ReturnExprOpt" */
    LookaheadDFA {
        states: &[None, Some(82), Some(83)],
        transitions: &[
            DFATransition(0, 10, 1),
            DFATransition(0, 23, 1),
            DFATransition(0, 24, 1),
            DFATransition(0, 25, 1),
            DFATransition(0, 26, 1),
            DFATransition(0, 27, 1),
            DFATransition(0, 29, 1),
            DFATransition(0, 30, 2),
            DFATransition(0, 31, 1),
            DFATransition(0, 33, 1),
            DFATransition(0, 34, 1),
            DFATransition(0, 35, 1),
        ],
        k: 1,
    },
    /* 54 - "Sep" */
    LookaheadDFA {
        states: &[None, Some(6), Some(7)],
        transitions: &[DFATransition(0, 6, 1), DFATransition(0, 7, 2)],
        k: 1,
    },
    /* 55 - "SepList" */
    LookaheadDFA {
        states: &[None, Some(8), Some(9)],
        transitions: &[
            DFATransition(0, 7, 1),
            DFATransition(0, 10, 2),
            DFATransition(0, 23, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
            DFATransition(0, 26, 2),
            DFATransition(0, 27, 2),
            DFATransition(0, 29, 2),
            DFATransition(0, 31, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
        ],
        k: 1,
    },
    /* 56 - "StorageMode" */
    LookaheadDFA {
        states: &[Some(21)],
        transitions: &[],
        k: 0,
    },
    /* 57 - "StringLiteral" */
    LookaheadDFA {
        states: &[Some(80)],
        transitions: &[],
        k: 0,
    },
    /* 58 - "Tuple" */
    LookaheadDFA {
        states: &[Some(96)],
        transitions: &[],
        k: 0,
    },
    /* 59 - "While" */
    LookaheadDFA {
        states: &[Some(95)],
        transitions: &[],
        k: 0,
    },
];

pub const PRODUCTIONS: &[Production; 100] = &[
    // 0 - Items: ItemsList /* Vec */;
    Production {
        lhs: 45,
        production: &[ParseType::N(46)],
    },
    // 1 - ItemsList: Item ItemsList;
    Production {
        lhs: 46,
        production: &[ParseType::N(46), ParseType::N(44)],
    },
    // 2 - ItemsList: ;
    Production {
        lhs: 46,
        production: &[],
    },
    // 3 - Item: Class;
    Production {
        lhs: 44,
        production: &[ParseType::N(13)],
    },
    // 4 - Item: Function;
    Production {
        lhs: 44,
        production: &[ParseType::N(37)],
    },
    // 5 - Class: "class" Identifier FieldList;
    Production {
        lhs: 13,
        production: &[ParseType::N(32), ParseType::N(40), ParseType::T(5)],
    },
    // 6 - Sep: ",";
    Production {
        lhs: 54,
        production: &[ParseType::T(6)],
    },
    // 7 - Sep: "\n" SepList /* Vec */;
    Production {
        lhs: 54,
        production: &[ParseType::N(55), ParseType::T(7)],
    },
    // 8 - SepList: "\n" SepList;
    Production {
        lhs: 55,
        production: &[ParseType::N(55), ParseType::T(7)],
    },
    // 9 - SepList: ;
    Production {
        lhs: 55,
        production: &[],
    },
    // 10 - MaybeTrailingComma: MaybeTrailingCommaOpt /* Option */;
    Production {
        lhs: 50,
        production: &[ParseType::N(51)],
    },
    // 11 - MaybeTrailingCommaOpt: ",";
    Production {
        lhs: 51,
        production: &[ParseType::T(6)],
    },
    // 12 - MaybeTrailingCommaOpt: ;
    Production {
        lhs: 51,
        production: &[],
    },
    // 13 - FieldList: "\(" FieldListSuffix;
    Production {
        lhs: 32,
        production: &[ParseType::N(34), ParseType::T(8)],
    },
    // 14 - FieldListSuffix: "\)";
    Production {
        lhs: 34,
        production: &[ParseType::T(9)],
    },
    // 15 - FieldListSuffix: Field FieldListList /* Vec */ MaybeTrailingComma "\)";
    Production {
        lhs: 34,
        production: &[
            ParseType::T(9),
            ParseType::N(50),
            ParseType::N(33),
            ParseType::N(31),
        ],
    },
    // 16 - FieldListList: Sep Field FieldListList;
    Production {
        lhs: 33,
        production: &[ParseType::N(33), ParseType::N(31), ParseType::N(54)],
    },
    // 17 - FieldListList: ;
    Production {
        lhs: 33,
        production: &[],
    },
    // 18 - Field: FieldOpt /* Option */ Identifier;
    Production {
        lhs: 31,
        production: &[ParseType::N(40), ParseType::N(35)],
    },
    // 19 - FieldOpt: StorageMode;
    Production {
        lhs: 35,
        production: &[ParseType::N(56)],
    },
    // 20 - FieldOpt: ;
    Production {
        lhs: 35,
        production: &[],
    },
    // 21 - StorageMode: "atomic";
    Production {
        lhs: 56,
        production: &[ParseType::T(10)],
    },
    // 22 - Function: FunctionOpt /* Option */ "fn" Identifier ArgumentList FunctionBody;
    Production {
        lhs: 37,
        production: &[
            ParseType::N(38),
            ParseType::N(0),
            ParseType::N(40),
            ParseType::T(11),
            ParseType::N(39),
        ],
    },
    // 23 - FunctionOpt: Effect;
    Production {
        lhs: 39,
        production: &[ParseType::N(17)],
    },
    // 24 - FunctionOpt: ;
    Production {
        lhs: 39,
        production: &[],
    },
    // 25 - Effect: "async";
    Production {
        lhs: 17,
        production: &[ParseType::T(12)],
    },
    // 26 - ArgumentList: "\(" ArgumentListSuffix;
    Production {
        lhs: 0,
        production: &[ParseType::N(2), ParseType::T(8)],
    },
    // 27 - ArgumentListSuffix: "\)";
    Production {
        lhs: 2,
        production: &[ParseType::T(9)],
    },
    // 28 - ArgumentListSuffix: Identifier ArgumentListList /* Vec */ MaybeTrailingComma "\)";
    Production {
        lhs: 2,
        production: &[
            ParseType::T(9),
            ParseType::N(50),
            ParseType::N(1),
            ParseType::N(40),
        ],
    },
    // 29 - ArgumentListList: Sep Identifier ArgumentListList;
    Production {
        lhs: 1,
        production: &[ParseType::N(1), ParseType::N(40), ParseType::N(54)],
    },
    // 30 - ArgumentListList: ;
    Production {
        lhs: 1,
        production: &[],
    },
    // 31 - FunctionBody: BlockExpr;
    Production {
        lhs: 38,
        production: &[ParseType::N(4)],
    },
    // 32 - Expr: LocalVariable;
    Production {
        lhs: 18,
        production: &[ParseType::N(47)],
    },
    // 33 - Expr: Expr5;
    Production {
        lhs: 18,
        production: &[ParseType::N(29)],
    },
    // 34 - Expr5: Expr4 Expr5List /* Vec */;
    Production {
        lhs: 29,
        production: &[ParseType::N(30), ParseType::N(27)],
    },
    // 35 - Expr5List: "(?:\+|-|/|\*|:)=" Expr4 Expr5List;
    Production {
        lhs: 30,
        production: &[ParseType::N(30), ParseType::N(27), ParseType::T(13)],
    },
    // 36 - Expr5List: ;
    Production {
        lhs: 30,
        production: &[],
    },
    // 37 - Expr4: Expr3 Expr4List /* Vec */;
    Production {
        lhs: 27,
        production: &[ParseType::N(28), ParseType::N(25)],
    },
    // 38 - Expr4List: "==|<|>" Expr3 Expr4List;
    Production {
        lhs: 28,
        production: &[ParseType::N(28), ParseType::N(25), ParseType::T(14)],
    },
    // 39 - Expr4List: ;
    Production {
        lhs: 28,
        production: &[],
    },
    // 40 - Expr3: Expr2 Expr3List /* Vec */;
    Production {
        lhs: 25,
        production: &[ParseType::N(26), ParseType::N(23)],
    },
    // 41 - Expr3List: "\+|-" Expr2 Expr3List;
    Production {
        lhs: 26,
        production: &[ParseType::N(26), ParseType::N(23), ParseType::T(15)],
    },
    // 42 - Expr3List: ;
    Production {
        lhs: 26,
        production: &[],
    },
    // 43 - Expr2: Expr1 Expr2List /* Vec */;
    Production {
        lhs: 23,
        production: &[ParseType::N(24), ParseType::N(20)],
    },
    // 44 - Expr2List: "/|\*" Expr1 Expr2List;
    Production {
        lhs: 24,
        production: &[ParseType::N(24), ParseType::N(20), ParseType::T(16)],
    },
    // 45 - Expr2List: ;
    Production {
        lhs: 24,
        production: &[],
    },
    // 46 - Expr1: Expr0 Expr1List /* Vec */;
    Production {
        lhs: 20,
        production: &[ParseType::N(21), ParseType::N(19)],
    },
    // 47 - Expr1List: Expr1ListGroup Expr1List;
    Production {
        lhs: 21,
        production: &[ParseType::N(21), ParseType::N(22)],
    },
    // 48 - Expr1ListGroup: DotExpr;
    Production {
        lhs: 22,
        production: &[ParseType::N(15)],
    },
    // 49 - Expr1ListGroup: CallArgumentList;
    Production {
        lhs: 22,
        production: &[ParseType::N(9)],
    },
    // 50 - Expr1List: ;
    Production {
        lhs: 21,
        production: &[],
    },
    // 51 - DotExpr: "\." DotSuffix;
    Production {
        lhs: 15,
        production: &[ParseType::N(16), ParseType::T(17)],
    },
    // 52 - DotSuffix: "await";
    Production {
        lhs: 16,
        production: &[ParseType::T(18)],
    },
    // 53 - DotSuffix: "share";
    Production {
        lhs: 16,
        production: &[ParseType::T(19)],
    },
    // 54 - DotSuffix: "give";
    Production {
        lhs: 16,
        production: &[ParseType::T(20)],
    },
    // 55 - DotSuffix: "lease";
    Production {
        lhs: 16,
        production: &[ParseType::T(21)],
    },
    // 56 - DotSuffix: Identifier;
    Production {
        lhs: 16,
        production: &[ParseType::N(40)],
    },
    // 57 - CallArgumentList: "\(" CallArgumentListSuffix;
    Production {
        lhs: 9,
        production: &[ParseType::N(11), ParseType::T(8)],
    },
    // 58 - CallArgumentListSuffix: "\)";
    Production {
        lhs: 11,
        production: &[ParseType::T(9)],
    },
    // 59 - CallArgumentListSuffix: CallArgument CallArgumentListList /* Vec */ MaybeTrailingComma "\)";
    Production {
        lhs: 11,
        production: &[
            ParseType::T(9),
            ParseType::N(50),
            ParseType::N(10),
            ParseType::N(8),
        ],
    },
    // 60 - CallArgumentListList: Sep CallArgument CallArgumentListList;
    Production {
        lhs: 10,
        production: &[ParseType::N(10), ParseType::N(8), ParseType::N(54)],
    },
    // 61 - CallArgumentListList: ;
    Production {
        lhs: 10,
        production: &[],
    },
    // 62 - CallArgument: CallArgumentOpt /* Option */ Expr;
    Production {
        lhs: 8,
        production: &[ParseType::N(18), ParseType::N(12)],
    },
    // 63 - CallArgumentOpt: Identifier ":";
    Production {
        lhs: 12,
        production: &[ParseType::T(22), ParseType::N(40)],
    },
    // 64 - CallArgumentOpt: ;
    Production {
        lhs: 12,
        production: &[],
    },
    // 65 - Expr0: Identifier;
    Production {
        lhs: 19,
        production: &[ParseType::N(40)],
    },
    // 66 - Expr0: BooleanLiteral;
    Production {
        lhs: 19,
        production: &[ParseType::N(7)],
    },
    // 67 - Expr0: FloatLiteral;
    Production {
        lhs: 19,
        production: &[ParseType::N(36)],
    },
    // 68 - Expr0: IntegerLiteral;
    Production {
        lhs: 19,
        production: &[ParseType::N(43)],
    },
    // 69 - Expr0: StringLiteral;
    Production {
        lhs: 19,
        production: &[ParseType::N(57)],
    },
    // 70 - Expr0: BlockExpr;
    Production {
        lhs: 19,
        production: &[ParseType::N(4)],
    },
    // 71 - Expr0: AtomicBlock;
    Production {
        lhs: 19,
        production: &[ParseType::N(3)],
    },
    // 72 - Expr0: IfExpr;
    Production {
        lhs: 19,
        production: &[ParseType::N(41)],
    },
    // 73 - Expr0: Loop;
    Production {
        lhs: 19,
        production: &[ParseType::N(49)],
    },
    // 74 - Expr0: While;
    Production {
        lhs: 19,
        production: &[ParseType::N(59)],
    },
    // 75 - Expr0: Tuple;
    Production {
        lhs: 19,
        production: &[ParseType::N(58)],
    },
    // 76 - BooleanLiteral: "true|false";
    Production {
        lhs: 7,
        production: &[ParseType::T(23)],
    },
    // 77 - Identifier: "[a-z|A-Z_][a-z|A-Z|0-9_]*";
    Production {
        lhs: 40,
        production: &[ParseType::T(24)],
    },
    // 78 - FloatLiteral: "[0-9][0-9_]*\.[0-9][0-9_]*";
    Production {
        lhs: 36,
        production: &[ParseType::T(25)],
    },
    // 79 - IntegerLiteral: "[0-9][0-9_]*";
    Production {
        lhs: 43,
        production: &[ParseType::T(26)],
    },
    // 80 - StringLiteral: "\u{0022}(?s:[^\u{0022}]*)\u{0022}";
    Production {
        lhs: 57,
        production: &[ParseType::T(27)],
    },
    // 81 - ReturnExpr: "return" ReturnExprOpt /* Option */;
    Production {
        lhs: 52,
        production: &[ParseType::N(53), ParseType::T(28)],
    },
    // 82 - ReturnExprOpt: Expr;
    Production {
        lhs: 53,
        production: &[ParseType::N(18)],
    },
    // 83 - ReturnExprOpt: ;
    Production {
        lhs: 53,
        production: &[],
    },
    // 84 - BlockExpr: "\{" BlockExprList /* Vec */ BlockExprOpt /* Option */ "\}";
    Production {
        lhs: 4,
        production: &[
            ParseType::T(30),
            ParseType::N(6),
            ParseType::N(5),
            ParseType::T(29),
        ],
    },
    // 85 - BlockExprList: Expr BlockExprList;
    Production {
        lhs: 5,
        production: &[ParseType::N(5), ParseType::N(18)],
    },
    // 86 - BlockExprList: ;
    Production {
        lhs: 5,
        production: &[],
    },
    // 87 - BlockExprOpt: ReturnExpr;
    Production {
        lhs: 6,
        production: &[ParseType::N(52)],
    },
    // 88 - BlockExprOpt: ;
    Production {
        lhs: 6,
        production: &[],
    },
    // 89 - AtomicBlock: "atomic" BlockExpr;
    Production {
        lhs: 3,
        production: &[ParseType::N(4), ParseType::T(10)],
    },
    // 90 - IfExpr: "if" Condition BlockExpr IfExprOpt /* Option */;
    Production {
        lhs: 41,
        production: &[
            ParseType::N(42),
            ParseType::N(4),
            ParseType::N(14),
            ParseType::T(31),
        ],
    },
    // 91 - IfExprOpt: "else" BlockExpr;
    Production {
        lhs: 42,
        production: &[ParseType::N(4), ParseType::T(32)],
    },
    // 92 - IfExprOpt: ;
    Production {
        lhs: 42,
        production: &[],
    },
    // 93 - Condition: Expr;
    Production {
        lhs: 14,
        production: &[ParseType::N(18)],
    },
    // 94 - Loop: "loop" BlockExpr;
    Production {
        lhs: 49,
        production: &[ParseType::N(4), ParseType::T(33)],
    },
    // 95 - While: "while" Condition BlockExpr;
    Production {
        lhs: 59,
        production: &[ParseType::N(4), ParseType::N(14), ParseType::T(34)],
    },
    // 96 - Tuple: "tuple";
    Production {
        lhs: 58,
        production: &[ParseType::T(35)],
    },
    // 97 - LocalVariable: LocalVariableOpt /* Option */ Identifier "=" Expr;
    Production {
        lhs: 47,
        production: &[
            ParseType::N(18),
            ParseType::T(36),
            ParseType::N(40),
            ParseType::N(48),
        ],
    },
    // 98 - LocalVariableOpt: StorageMode;
    Production {
        lhs: 48,
        production: &[ParseType::N(56)],
    },
    // 99 - LocalVariableOpt: ;
    Production {
        lhs: 48,
        production: &[],
    },
];

lazy_static! {
    static ref TOKENIZERS: Vec<(&'static str, Tokenizer)> = vec![(
        "INITIAL",
        Tokenizer::build(TERMINALS, SCANNER_0.0, SCANNER_0.1).unwrap()
    ),];
}

pub fn parse<'t, T>(
    input: &'t str,
    file_name: T,
    user_actions: &mut dyn UserActionsTrait<'t>,
) -> Result<Tree<ParseTreeType<'t>>>
where
    T: AsRef<Path>,
{
    let mut llk_parser = LLKParser::new(
        45,
        LOOKAHEAD_AUTOMATA,
        PRODUCTIONS,
        TERMINAL_NAMES,
        NON_TERMINALS,
    );
    let token_stream =
        RefCell::new(TokenStream::new(input, file_name, &TOKENIZERS, MAX_K).unwrap());
    let result = llk_parser.parse(token_stream, user_actions);
    match result {
        Ok(()) => Ok(llk_parser.parse_tree),
        Err(e) => Err(e),
    }
}
