// ---------------------------------------------------------
// This file was generated by parol.
// It is not intended for manual editing and changes will be
// lost after next build.
// ---------------------------------------------------------

use id_tree::Tree;
use miette::Result;
use parol_runtime::lexer::{TokenStream, Tokenizer};
#[allow(unused_imports)]
use parol_runtime::parser::{
    DFATransition, LLKParser, LookaheadDFA, ParseTreeType, ParseType, Production, UserActionsTrait,
};
use std::cell::RefCell;
use std::path::Path;

use parol_runtime::lexer::tokenizer::{
    ERROR_TOKEN, NEW_LINE_TOKEN, UNMATCHABLE_TOKEN, WHITESPACE_TOKEN,
};

pub const TERMINALS: &[&str; 46] = &[
    /*  0 */ UNMATCHABLE_TOKEN,
    /*  1 */ UNMATCHABLE_TOKEN,
    /*  2 */ UNMATCHABLE_TOKEN,
    /*  3 */ UNMATCHABLE_TOKEN,
    /*  4 */ UNMATCHABLE_TOKEN,
    /*  5 */ r###"class"###,
    /*  6 */ r###"\("###,
    /*  7 */ r###"\)"###,
    /*  8 */ r###","###,
    /*  9 */ r###"atomic"###,
    /* 10 */ r###"fn"###,
    /* 11 */ r###"async"###,
    /* 12 */ r###"return"###,
    /* 13 */ r###"\+="###,
    /* 14 */ r###"-="###,
    /* 15 */ r###"/="###,
    /* 16 */ r###"\*="###,
    /* 17 */ r###":="###,
    /* 18 */ r###"=="###,
    /* 19 */ r###"<"###,
    /* 20 */ r###">"###,
    /* 21 */ r###"\+"###,
    /* 22 */ r###"-"###,
    /* 23 */ r###"/"###,
    /* 24 */ r###"\*"###,
    /* 25 */ r###"\."###,
    /* 26 */ r###"await"###,
    /* 27 */ r###"share"###,
    /* 28 */ r###"give"###,
    /* 29 */ r###"lease"###,
    /* 30 */ r###":"###,
    /* 31 */ r###"true"###,
    /* 32 */ r###"false"###,
    /* 33 */ r###"[a-z|A-Z_][a-z|A-Z|0-9_]*"###,
    /* 34 */ r###"[0-9][0-9_]*\.[0-9][0-9_]*"###,
    /* 35 */ r###"[0-9][0-9_]*"###,
    /* 36 */ r###"\u{0022}(?s:[^\u{0022}]*)\u{0022}"###,
    /* 37 */ r###"\{"###,
    /* 38 */ r###"\}"###,
    /* 39 */ r###"if"###,
    /* 40 */ r###"else"###,
    /* 41 */ r###"loop"###,
    /* 42 */ r###"while"###,
    /* 43 */ r###"tuple"###,
    /* 44 */ r###"="###,
    /* 45 */ ERROR_TOKEN,
];

pub const TERMINAL_NAMES: &[&str; 46] = &[
    /*  0 */ "EndOfInput",
    /*  1 */ "Newline",
    /*  2 */ "Whitespace",
    /*  3 */ "LineComment",
    /*  4 */ "BlockComment",
    /*  5 */ "Class",
    /*  6 */ "LParen",
    /*  7 */ "RParen",
    /*  8 */ "Comma",
    /*  9 */ "StorageMode",
    /* 10 */ "Fn",
    /* 11 */ "Effect",
    /* 12 */ "ReturnWithoutExpr",
    /* 13 */ "PlusEqu",
    /* 14 */ "MinusEqu",
    /* 15 */ "SlashEqu",
    /* 16 */ "StarEqu",
    /* 17 */ "ColonEqu",
    /* 18 */ "EquEqu",
    /* 19 */ "LT",
    /* 20 */ "GT",
    /* 21 */ "Plus",
    /* 22 */ "Minus",
    /* 23 */ "Slash",
    /* 24 */ "Star",
    /* 25 */ "Dot",
    /* 26 */ "Await",
    /* 27 */ "Share",
    /* 28 */ "Give",
    /* 29 */ "Lease",
    /* 30 */ "Colon",
    /* 31 */ "True",
    /* 32 */ "False",
    /* 33 */ "Identifier",
    /* 34 */ "FloatLiteral",
    /* 35 */ "IntegerLiteral",
    /* 36 */ "StringLiteral",
    /* 37 */ "LBrace",
    /* 38 */ "RBrace",
    /* 39 */ "If",
    /* 40 */ "Else",
    /* 41 */ "Loop",
    /* 42 */ "While",
    /* 43 */ "Tuple",
    /* 44 */ "Equ",
    /* 45 */ "Error",
];

/* SCANNER_0: "INITIAL" */
const SCANNER_0: (&[&str; 5], &[usize; 40]) = (
    &[
        /*  0 */ UNMATCHABLE_TOKEN,
        /*  1 */ NEW_LINE_TOKEN,
        /*  2 */ WHITESPACE_TOKEN,
        /*  3 */ r###"(#.*(\r\n|\r|\n|$))"###,
        /*  4 */ UNMATCHABLE_TOKEN,
    ],
    &[
        5,  /* Class */
        6,  /* LParen */
        7,  /* RParen */
        8,  /* Comma */
        9,  /* StorageMode */
        10, /* Fn */
        11, /* Effect */
        12, /* ReturnWithoutExpr */
        13, /* PlusEqu */
        14, /* MinusEqu */
        15, /* SlashEqu */
        16, /* StarEqu */
        17, /* ColonEqu */
        18, /* EquEqu */
        19, /* LT */
        20, /* GT */
        21, /* Plus */
        22, /* Minus */
        23, /* Slash */
        24, /* Star */
        25, /* Dot */
        26, /* Await */
        27, /* Share */
        28, /* Give */
        29, /* Lease */
        30, /* Colon */
        31, /* True */
        32, /* False */
        33, /* Identifier */
        34, /* FloatLiteral */
        35, /* IntegerLiteral */
        36, /* StringLiteral */
        37, /* LBrace */
        38, /* RBrace */
        39, /* If */
        40, /* Else */
        41, /* Loop */
        42, /* While */
        43, /* Tuple */
        44, /* Equ */
    ],
);

const MAX_K: usize = 2;

pub const NON_TERMINALS: &[&str; 63] = &[
    /*  0 */ "ArgumentList",
    /*  1 */ "ArgumentListList",
    /*  2 */ "ArgumentListSuffix",
    /*  3 */ "AtomicBlock",
    /*  4 */ "BlockExpr",
    /*  5 */ "BlockExprList",
    /*  6 */ "BlockExprOpt",
    /*  7 */ "BooleanLiteral",
    /*  8 */ "CallArgument",
    /*  9 */ "CallArgumentList",
    /* 10 */ "CallArgumentListList",
    /* 11 */ "CallArgumentListSuffix",
    /* 12 */ "CallArgumentOpt",
    /* 13 */ "Class",
    /* 14 */ "Condition",
    /* 15 */ "DotExpr",
    /* 16 */ "DotSuffix",
    /* 17 */ "Effect",
    /* 18 */ "Expr",
    /* 19 */ "Expr0",
    /* 20 */ "Expr1",
    /* 21 */ "Expr1List",
    /* 22 */ "Expr1ListGroup",
    /* 23 */ "Expr2",
    /* 24 */ "Expr2List",
    /* 25 */ "Expr2ListGroup",
    /* 26 */ "Expr3",
    /* 27 */ "Expr3List",
    /* 28 */ "Expr3ListGroup",
    /* 29 */ "Expr4",
    /* 30 */ "Expr4List",
    /* 31 */ "Expr4ListGroup",
    /* 32 */ "Expr5",
    /* 33 */ "Expr5List",
    /* 34 */ "Expr5ListGroup",
    /* 35 */ "Field",
    /* 36 */ "FieldList",
    /* 37 */ "FieldListList",
    /* 38 */ "FieldListOpt",
    /* 39 */ "FieldListSuffix",
    /* 40 */ "FieldOpt",
    /* 41 */ "FloatLiteral",
    /* 42 */ "Function",
    /* 43 */ "FunctionBody",
    /* 44 */ "FunctionOpt",
    /* 45 */ "Identifier",
    /* 46 */ "IfExpr",
    /* 47 */ "IfExprOpt",
    /* 48 */ "IntegerLiteral",
    /* 49 */ "Item",
    /* 50 */ "Items",
    /* 51 */ "ItemsList",
    /* 52 */ "LocalVariable",
    /* 53 */ "LocalVariableOpt",
    /* 54 */ "Loop",
    /* 55 */ "MaybeTrailingComma",
    /* 56 */ "MaybeTrailingCommaOpt",
    /* 57 */ "ReturnWithExpr",
    /* 58 */ "ReturnWithoutExpr",
    /* 59 */ "StorageMode",
    /* 60 */ "StringLiteral",
    /* 61 */ "Tuple",
    /* 62 */ "While",
];

pub const LOOKAHEAD_AUTOMATA: &[LookaheadDFA; 63] = &[
    /* 0 - "ArgumentList" */
    LookaheadDFA {
        states: &[Some(21)],
        transitions: &[],
        k: 0,
    },
    /* 1 - "ArgumentListList" */
    LookaheadDFA {
        states: &[None, Some(24), Some(25)],
        transitions: &[DFATransition(0, 7, 2), DFATransition(0, 8, 1)],
        k: 1,
    },
    /* 2 - "ArgumentListSuffix" */
    LookaheadDFA {
        states: &[None, Some(22), Some(23)],
        transitions: &[DFATransition(0, 7, 1), DFATransition(0, 33, 2)],
        k: 1,
    },
    /* 3 - "AtomicBlock" */
    LookaheadDFA {
        states: &[Some(100)],
        transitions: &[],
        k: 0,
    },
    /* 4 - "BlockExpr" */
    LookaheadDFA {
        states: &[Some(95)],
        transitions: &[],
        k: 0,
    },
    /* 5 - "BlockExprList" */
    LookaheadDFA {
        states: &[
            None,
            None,
            Some(96),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(97),
        ],
        transitions: &[
            DFATransition(0, 9, 1),
            DFATransition(0, 12, 3),
            DFATransition(0, 31, 4),
            DFATransition(0, 32, 5),
            DFATransition(0, 33, 6),
            DFATransition(0, 34, 7),
            DFATransition(0, 35, 8),
            DFATransition(0, 36, 9),
            DFATransition(0, 37, 10),
            DFATransition(0, 38, 15),
            DFATransition(0, 39, 11),
            DFATransition(0, 41, 12),
            DFATransition(0, 42, 13),
            DFATransition(0, 43, 14),
            DFATransition(1, 33, 2),
            DFATransition(1, 37, 2),
            DFATransition(3, 9, 2),
            DFATransition(3, 12, 2),
            DFATransition(3, 31, 2),
            DFATransition(3, 32, 2),
            DFATransition(3, 33, 2),
            DFATransition(3, 34, 2),
            DFATransition(3, 35, 2),
            DFATransition(3, 36, 2),
            DFATransition(3, 37, 2),
            DFATransition(3, 38, 16),
            DFATransition(3, 39, 2),
            DFATransition(3, 41, 2),
            DFATransition(3, 42, 2),
            DFATransition(3, 43, 2),
            DFATransition(4, 6, 2),
            DFATransition(4, 9, 2),
            DFATransition(4, 12, 2),
            DFATransition(4, 13, 2),
            DFATransition(4, 14, 2),
            DFATransition(4, 15, 2),
            DFATransition(4, 16, 2),
            DFATransition(4, 17, 2),
            DFATransition(4, 18, 2),
            DFATransition(4, 19, 2),
            DFATransition(4, 20, 2),
            DFATransition(4, 21, 2),
            DFATransition(4, 22, 2),
            DFATransition(4, 23, 2),
            DFATransition(4, 24, 2),
            DFATransition(4, 25, 2),
            DFATransition(4, 31, 2),
            DFATransition(4, 32, 2),
            DFATransition(4, 33, 2),
            DFATransition(4, 34, 2),
            DFATransition(4, 35, 2),
            DFATransition(4, 36, 2),
            DFATransition(4, 37, 2),
            DFATransition(4, 38, 2),
            DFATransition(4, 39, 2),
            DFATransition(4, 41, 2),
            DFATransition(4, 42, 2),
            DFATransition(4, 43, 2),
            DFATransition(5, 6, 2),
            DFATransition(5, 9, 2),
            DFATransition(5, 12, 2),
            DFATransition(5, 13, 2),
            DFATransition(5, 14, 2),
            DFATransition(5, 15, 2),
            DFATransition(5, 16, 2),
            DFATransition(5, 17, 2),
            DFATransition(5, 18, 2),
            DFATransition(5, 19, 2),
            DFATransition(5, 20, 2),
            DFATransition(5, 21, 2),
            DFATransition(5, 22, 2),
            DFATransition(5, 23, 2),
            DFATransition(5, 24, 2),
            DFATransition(5, 25, 2),
            DFATransition(5, 31, 2),
            DFATransition(5, 32, 2),
            DFATransition(5, 33, 2),
            DFATransition(5, 34, 2),
            DFATransition(5, 35, 2),
            DFATransition(5, 36, 2),
            DFATransition(5, 37, 2),
            DFATransition(5, 38, 2),
            DFATransition(5, 39, 2),
            DFATransition(5, 41, 2),
            DFATransition(5, 42, 2),
            DFATransition(5, 43, 2),
            DFATransition(6, 6, 2),
            DFATransition(6, 9, 2),
            DFATransition(6, 12, 2),
            DFATransition(6, 13, 2),
            DFATransition(6, 14, 2),
            DFATransition(6, 15, 2),
            DFATransition(6, 16, 2),
            DFATransition(6, 17, 2),
            DFATransition(6, 18, 2),
            DFATransition(6, 19, 2),
            DFATransition(6, 20, 2),
            DFATransition(6, 21, 2),
            DFATransition(6, 22, 2),
            DFATransition(6, 23, 2),
            DFATransition(6, 24, 2),
            DFATransition(6, 25, 2),
            DFATransition(6, 31, 2),
            DFATransition(6, 32, 2),
            DFATransition(6, 33, 2),
            DFATransition(6, 34, 2),
            DFATransition(6, 35, 2),
            DFATransition(6, 36, 2),
            DFATransition(6, 37, 2),
            DFATransition(6, 38, 2),
            DFATransition(6, 39, 2),
            DFATransition(6, 41, 2),
            DFATransition(6, 42, 2),
            DFATransition(6, 43, 2),
            DFATransition(6, 44, 2),
            DFATransition(7, 6, 2),
            DFATransition(7, 9, 2),
            DFATransition(7, 12, 2),
            DFATransition(7, 13, 2),
            DFATransition(7, 14, 2),
            DFATransition(7, 15, 2),
            DFATransition(7, 16, 2),
            DFATransition(7, 17, 2),
            DFATransition(7, 18, 2),
            DFATransition(7, 19, 2),
            DFATransition(7, 20, 2),
            DFATransition(7, 21, 2),
            DFATransition(7, 22, 2),
            DFATransition(7, 23, 2),
            DFATransition(7, 24, 2),
            DFATransition(7, 25, 2),
            DFATransition(7, 31, 2),
            DFATransition(7, 32, 2),
            DFATransition(7, 33, 2),
            DFATransition(7, 34, 2),
            DFATransition(7, 35, 2),
            DFATransition(7, 36, 2),
            DFATransition(7, 37, 2),
            DFATransition(7, 38, 2),
            DFATransition(7, 39, 2),
            DFATransition(7, 41, 2),
            DFATransition(7, 42, 2),
            DFATransition(7, 43, 2),
            DFATransition(8, 6, 2),
            DFATransition(8, 9, 2),
            DFATransition(8, 12, 2),
            DFATransition(8, 13, 2),
            DFATransition(8, 14, 2),
            DFATransition(8, 15, 2),
            DFATransition(8, 16, 2),
            DFATransition(8, 17, 2),
            DFATransition(8, 18, 2),
            DFATransition(8, 19, 2),
            DFATransition(8, 20, 2),
            DFATransition(8, 21, 2),
            DFATransition(8, 22, 2),
            DFATransition(8, 23, 2),
            DFATransition(8, 24, 2),
            DFATransition(8, 25, 2),
            DFATransition(8, 31, 2),
            DFATransition(8, 32, 2),
            DFATransition(8, 33, 2),
            DFATransition(8, 34, 2),
            DFATransition(8, 35, 2),
            DFATransition(8, 36, 2),
            DFATransition(8, 37, 2),
            DFATransition(8, 38, 2),
            DFATransition(8, 39, 2),
            DFATransition(8, 41, 2),
            DFATransition(8, 42, 2),
            DFATransition(8, 43, 2),
            DFATransition(9, 6, 2),
            DFATransition(9, 9, 2),
            DFATransition(9, 12, 2),
            DFATransition(9, 13, 2),
            DFATransition(9, 14, 2),
            DFATransition(9, 15, 2),
            DFATransition(9, 16, 2),
            DFATransition(9, 17, 2),
            DFATransition(9, 18, 2),
            DFATransition(9, 19, 2),
            DFATransition(9, 20, 2),
            DFATransition(9, 21, 2),
            DFATransition(9, 22, 2),
            DFATransition(9, 23, 2),
            DFATransition(9, 24, 2),
            DFATransition(9, 25, 2),
            DFATransition(9, 31, 2),
            DFATransition(9, 32, 2),
            DFATransition(9, 33, 2),
            DFATransition(9, 34, 2),
            DFATransition(9, 35, 2),
            DFATransition(9, 36, 2),
            DFATransition(9, 37, 2),
            DFATransition(9, 38, 2),
            DFATransition(9, 39, 2),
            DFATransition(9, 41, 2),
            DFATransition(9, 42, 2),
            DFATransition(9, 43, 2),
            DFATransition(10, 9, 2),
            DFATransition(10, 12, 2),
            DFATransition(10, 31, 2),
            DFATransition(10, 32, 2),
            DFATransition(10, 33, 2),
            DFATransition(10, 34, 2),
            DFATransition(10, 35, 2),
            DFATransition(10, 36, 2),
            DFATransition(10, 37, 2),
            DFATransition(10, 38, 2),
            DFATransition(10, 39, 2),
            DFATransition(10, 41, 2),
            DFATransition(10, 42, 2),
            DFATransition(10, 43, 2),
            DFATransition(11, 9, 2),
            DFATransition(11, 12, 2),
            DFATransition(11, 31, 2),
            DFATransition(11, 32, 2),
            DFATransition(11, 33, 2),
            DFATransition(11, 34, 2),
            DFATransition(11, 35, 2),
            DFATransition(11, 36, 2),
            DFATransition(11, 37, 2),
            DFATransition(11, 39, 2),
            DFATransition(11, 41, 2),
            DFATransition(11, 42, 2),
            DFATransition(11, 43, 2),
            DFATransition(12, 37, 2),
            DFATransition(13, 9, 2),
            DFATransition(13, 12, 2),
            DFATransition(13, 31, 2),
            DFATransition(13, 32, 2),
            DFATransition(13, 33, 2),
            DFATransition(13, 34, 2),
            DFATransition(13, 35, 2),
            DFATransition(13, 36, 2),
            DFATransition(13, 37, 2),
            DFATransition(13, 39, 2),
            DFATransition(13, 41, 2),
            DFATransition(13, 42, 2),
            DFATransition(13, 43, 2),
            DFATransition(14, 6, 2),
            DFATransition(14, 9, 2),
            DFATransition(14, 12, 2),
            DFATransition(14, 13, 2),
            DFATransition(14, 14, 2),
            DFATransition(14, 15, 2),
            DFATransition(14, 16, 2),
            DFATransition(14, 17, 2),
            DFATransition(14, 18, 2),
            DFATransition(14, 19, 2),
            DFATransition(14, 20, 2),
            DFATransition(14, 21, 2),
            DFATransition(14, 22, 2),
            DFATransition(14, 23, 2),
            DFATransition(14, 24, 2),
            DFATransition(14, 25, 2),
            DFATransition(14, 31, 2),
            DFATransition(14, 32, 2),
            DFATransition(14, 33, 2),
            DFATransition(14, 34, 2),
            DFATransition(14, 35, 2),
            DFATransition(14, 36, 2),
            DFATransition(14, 37, 2),
            DFATransition(14, 38, 2),
            DFATransition(14, 39, 2),
            DFATransition(14, 41, 2),
            DFATransition(14, 42, 2),
            DFATransition(14, 43, 2),
            DFATransition(15, 0, 16),
            DFATransition(15, 5, 16),
            DFATransition(15, 6, 16),
            DFATransition(15, 7, 16),
            DFATransition(15, 8, 16),
            DFATransition(15, 9, 16),
            DFATransition(15, 10, 16),
            DFATransition(15, 11, 16),
            DFATransition(15, 12, 16),
            DFATransition(15, 13, 16),
            DFATransition(15, 14, 16),
            DFATransition(15, 15, 16),
            DFATransition(15, 16, 16),
            DFATransition(15, 17, 16),
            DFATransition(15, 18, 16),
            DFATransition(15, 19, 16),
            DFATransition(15, 20, 16),
            DFATransition(15, 21, 16),
            DFATransition(15, 22, 16),
            DFATransition(15, 23, 16),
            DFATransition(15, 24, 16),
            DFATransition(15, 25, 16),
            DFATransition(15, 31, 16),
            DFATransition(15, 32, 16),
            DFATransition(15, 33, 16),
            DFATransition(15, 34, 16),
            DFATransition(15, 35, 16),
            DFATransition(15, 36, 16),
            DFATransition(15, 37, 16),
            DFATransition(15, 38, 16),
            DFATransition(15, 39, 16),
            DFATransition(15, 40, 16),
            DFATransition(15, 41, 16),
            DFATransition(15, 42, 16),
            DFATransition(15, 43, 16),
        ],
        k: 2,
    },
    /* 6 - "BlockExprOpt" */
    LookaheadDFA {
        states: &[None, Some(98), Some(99)],
        transitions: &[DFATransition(0, 12, 1), DFATransition(0, 38, 2)],
        k: 1,
    },
    /* 7 - "BooleanLiteral" */
    LookaheadDFA {
        states: &[None, Some(89), Some(90)],
        transitions: &[DFATransition(0, 31, 1), DFATransition(0, 32, 2)],
        k: 1,
    },
    /* 8 - "CallArgument" */
    LookaheadDFA {
        states: &[Some(75)],
        transitions: &[],
        k: 0,
    },
    /* 9 - "CallArgumentList" */
    LookaheadDFA {
        states: &[Some(67)],
        transitions: &[],
        k: 0,
    },
    /* 10 - "CallArgumentListList" */
    LookaheadDFA {
        states: &[None, None, Some(70), None, Some(71)],
        transitions: &[
            DFATransition(0, 7, 3),
            DFATransition(0, 8, 1),
            DFATransition(1, 7, 4),
            DFATransition(1, 9, 2),
            DFATransition(1, 12, 2),
            DFATransition(1, 31, 2),
            DFATransition(1, 32, 2),
            DFATransition(1, 33, 2),
            DFATransition(1, 34, 2),
            DFATransition(1, 35, 2),
            DFATransition(1, 36, 2),
            DFATransition(1, 37, 2),
            DFATransition(1, 39, 2),
            DFATransition(1, 41, 2),
            DFATransition(1, 42, 2),
            DFATransition(1, 43, 2),
            DFATransition(3, 6, 4),
            DFATransition(3, 7, 4),
            DFATransition(3, 8, 4),
            DFATransition(3, 9, 4),
            DFATransition(3, 12, 4),
            DFATransition(3, 13, 4),
            DFATransition(3, 14, 4),
            DFATransition(3, 15, 4),
            DFATransition(3, 16, 4),
            DFATransition(3, 17, 4),
            DFATransition(3, 18, 4),
            DFATransition(3, 19, 4),
            DFATransition(3, 20, 4),
            DFATransition(3, 21, 4),
            DFATransition(3, 22, 4),
            DFATransition(3, 23, 4),
            DFATransition(3, 24, 4),
            DFATransition(3, 25, 4),
            DFATransition(3, 31, 4),
            DFATransition(3, 32, 4),
            DFATransition(3, 33, 4),
            DFATransition(3, 34, 4),
            DFATransition(3, 35, 4),
            DFATransition(3, 36, 4),
            DFATransition(3, 37, 4),
            DFATransition(3, 38, 4),
            DFATransition(3, 39, 4),
            DFATransition(3, 41, 4),
            DFATransition(3, 42, 4),
            DFATransition(3, 43, 4),
        ],
        k: 2,
    },
    /* 11 - "CallArgumentListSuffix" */
    LookaheadDFA {
        states: &[None, Some(68), Some(69)],
        transitions: &[
            DFATransition(0, 7, 1),
            DFATransition(0, 9, 2),
            DFATransition(0, 12, 2),
            DFATransition(0, 31, 2),
            DFATransition(0, 32, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
            DFATransition(0, 36, 2),
            DFATransition(0, 37, 2),
            DFATransition(0, 39, 2),
            DFATransition(0, 41, 2),
            DFATransition(0, 42, 2),
            DFATransition(0, 43, 2),
        ],
        k: 1,
    },
    /* 12 - "CallArgumentOpt" */
    LookaheadDFA {
        states: &[
            None,
            None,
            Some(76),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(77),
        ],
        transitions: &[
            DFATransition(0, 9, 3),
            DFATransition(0, 12, 4),
            DFATransition(0, 31, 5),
            DFATransition(0, 32, 6),
            DFATransition(0, 33, 1),
            DFATransition(0, 34, 7),
            DFATransition(0, 35, 8),
            DFATransition(0, 36, 9),
            DFATransition(0, 37, 10),
            DFATransition(0, 39, 11),
            DFATransition(0, 41, 12),
            DFATransition(0, 42, 13),
            DFATransition(0, 43, 14),
            DFATransition(1, 6, 15),
            DFATransition(1, 7, 15),
            DFATransition(1, 8, 15),
            DFATransition(1, 13, 15),
            DFATransition(1, 14, 15),
            DFATransition(1, 15, 15),
            DFATransition(1, 16, 15),
            DFATransition(1, 17, 15),
            DFATransition(1, 18, 15),
            DFATransition(1, 19, 15),
            DFATransition(1, 20, 15),
            DFATransition(1, 21, 15),
            DFATransition(1, 22, 15),
            DFATransition(1, 23, 15),
            DFATransition(1, 24, 15),
            DFATransition(1, 25, 15),
            DFATransition(1, 30, 2),
            DFATransition(1, 44, 15),
            DFATransition(3, 33, 15),
            DFATransition(3, 37, 15),
            DFATransition(4, 9, 15),
            DFATransition(4, 12, 15),
            DFATransition(4, 31, 15),
            DFATransition(4, 32, 15),
            DFATransition(4, 33, 15),
            DFATransition(4, 34, 15),
            DFATransition(4, 35, 15),
            DFATransition(4, 36, 15),
            DFATransition(4, 37, 15),
            DFATransition(4, 39, 15),
            DFATransition(4, 41, 15),
            DFATransition(4, 42, 15),
            DFATransition(4, 43, 15),
            DFATransition(5, 6, 15),
            DFATransition(5, 7, 15),
            DFATransition(5, 8, 15),
            DFATransition(5, 13, 15),
            DFATransition(5, 14, 15),
            DFATransition(5, 15, 15),
            DFATransition(5, 16, 15),
            DFATransition(5, 17, 15),
            DFATransition(5, 18, 15),
            DFATransition(5, 19, 15),
            DFATransition(5, 20, 15),
            DFATransition(5, 21, 15),
            DFATransition(5, 22, 15),
            DFATransition(5, 23, 15),
            DFATransition(5, 24, 15),
            DFATransition(5, 25, 15),
            DFATransition(6, 6, 15),
            DFATransition(6, 7, 15),
            DFATransition(6, 8, 15),
            DFATransition(6, 13, 15),
            DFATransition(6, 14, 15),
            DFATransition(6, 15, 15),
            DFATransition(6, 16, 15),
            DFATransition(6, 17, 15),
            DFATransition(6, 18, 15),
            DFATransition(6, 19, 15),
            DFATransition(6, 20, 15),
            DFATransition(6, 21, 15),
            DFATransition(6, 22, 15),
            DFATransition(6, 23, 15),
            DFATransition(6, 24, 15),
            DFATransition(6, 25, 15),
            DFATransition(7, 6, 15),
            DFATransition(7, 7, 15),
            DFATransition(7, 8, 15),
            DFATransition(7, 13, 15),
            DFATransition(7, 14, 15),
            DFATransition(7, 15, 15),
            DFATransition(7, 16, 15),
            DFATransition(7, 17, 15),
            DFATransition(7, 18, 15),
            DFATransition(7, 19, 15),
            DFATransition(7, 20, 15),
            DFATransition(7, 21, 15),
            DFATransition(7, 22, 15),
            DFATransition(7, 23, 15),
            DFATransition(7, 24, 15),
            DFATransition(7, 25, 15),
            DFATransition(8, 6, 15),
            DFATransition(8, 7, 15),
            DFATransition(8, 8, 15),
            DFATransition(8, 13, 15),
            DFATransition(8, 14, 15),
            DFATransition(8, 15, 15),
            DFATransition(8, 16, 15),
            DFATransition(8, 17, 15),
            DFATransition(8, 18, 15),
            DFATransition(8, 19, 15),
            DFATransition(8, 20, 15),
            DFATransition(8, 21, 15),
            DFATransition(8, 22, 15),
            DFATransition(8, 23, 15),
            DFATransition(8, 24, 15),
            DFATransition(8, 25, 15),
            DFATransition(9, 6, 15),
            DFATransition(9, 7, 15),
            DFATransition(9, 8, 15),
            DFATransition(9, 13, 15),
            DFATransition(9, 14, 15),
            DFATransition(9, 15, 15),
            DFATransition(9, 16, 15),
            DFATransition(9, 17, 15),
            DFATransition(9, 18, 15),
            DFATransition(9, 19, 15),
            DFATransition(9, 20, 15),
            DFATransition(9, 21, 15),
            DFATransition(9, 22, 15),
            DFATransition(9, 23, 15),
            DFATransition(9, 24, 15),
            DFATransition(9, 25, 15),
            DFATransition(10, 9, 15),
            DFATransition(10, 12, 15),
            DFATransition(10, 31, 15),
            DFATransition(10, 32, 15),
            DFATransition(10, 33, 15),
            DFATransition(10, 34, 15),
            DFATransition(10, 35, 15),
            DFATransition(10, 36, 15),
            DFATransition(10, 37, 15),
            DFATransition(10, 38, 15),
            DFATransition(10, 39, 15),
            DFATransition(10, 41, 15),
            DFATransition(10, 42, 15),
            DFATransition(10, 43, 15),
            DFATransition(11, 9, 15),
            DFATransition(11, 12, 15),
            DFATransition(11, 31, 15),
            DFATransition(11, 32, 15),
            DFATransition(11, 33, 15),
            DFATransition(11, 34, 15),
            DFATransition(11, 35, 15),
            DFATransition(11, 36, 15),
            DFATransition(11, 37, 15),
            DFATransition(11, 39, 15),
            DFATransition(11, 41, 15),
            DFATransition(11, 42, 15),
            DFATransition(11, 43, 15),
            DFATransition(12, 37, 15),
            DFATransition(13, 9, 15),
            DFATransition(13, 12, 15),
            DFATransition(13, 31, 15),
            DFATransition(13, 32, 15),
            DFATransition(13, 33, 15),
            DFATransition(13, 34, 15),
            DFATransition(13, 35, 15),
            DFATransition(13, 36, 15),
            DFATransition(13, 37, 15),
            DFATransition(13, 39, 15),
            DFATransition(13, 41, 15),
            DFATransition(13, 42, 15),
            DFATransition(13, 43, 15),
            DFATransition(14, 6, 15),
            DFATransition(14, 7, 15),
            DFATransition(14, 8, 15),
            DFATransition(14, 13, 15),
            DFATransition(14, 14, 15),
            DFATransition(14, 15, 15),
            DFATransition(14, 16, 15),
            DFATransition(14, 17, 15),
            DFATransition(14, 18, 15),
            DFATransition(14, 19, 15),
            DFATransition(14, 20, 15),
            DFATransition(14, 21, 15),
            DFATransition(14, 22, 15),
            DFATransition(14, 23, 15),
            DFATransition(14, 24, 15),
            DFATransition(14, 25, 15),
        ],
        k: 2,
    },
    /* 13 - "Class" */
    LookaheadDFA {
        states: &[Some(5)],
        transitions: &[],
        k: 0,
    },
    /* 14 - "Condition" */
    LookaheadDFA {
        states: &[Some(104)],
        transitions: &[],
        k: 0,
    },
    /* 15 - "DotExpr" */
    LookaheadDFA {
        states: &[Some(61)],
        transitions: &[],
        k: 0,
    },
    /* 16 - "DotSuffix" */
    LookaheadDFA {
        states: &[None, Some(62), Some(63), Some(64), Some(65), Some(66)],
        transitions: &[
            DFATransition(0, 26, 1),
            DFATransition(0, 27, 2),
            DFATransition(0, 28, 3),
            DFATransition(0, 29, 4),
            DFATransition(0, 33, 5),
        ],
        k: 1,
    },
    /* 17 - "Effect" */
    LookaheadDFA {
        states: &[Some(20)],
        transitions: &[],
        k: 0,
    },
    /* 18 - "Expr" */
    LookaheadDFA {
        states: &[
            None,
            None,
            Some(27),
            None,
            None,
            Some(28),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(29),
        ],
        transitions: &[
            DFATransition(0, 9, 1),
            DFATransition(0, 12, 4),
            DFATransition(0, 31, 6),
            DFATransition(0, 32, 7),
            DFATransition(0, 33, 3),
            DFATransition(0, 34, 8),
            DFATransition(0, 35, 9),
            DFATransition(0, 36, 10),
            DFATransition(0, 37, 11),
            DFATransition(0, 39, 12),
            DFATransition(0, 41, 13),
            DFATransition(0, 42, 14),
            DFATransition(0, 43, 15),
            DFATransition(1, 33, 2),
            DFATransition(1, 37, 16),
            DFATransition(3, 6, 16),
            DFATransition(3, 7, 16),
            DFATransition(3, 8, 16),
            DFATransition(3, 9, 16),
            DFATransition(3, 12, 16),
            DFATransition(3, 13, 16),
            DFATransition(3, 14, 16),
            DFATransition(3, 15, 16),
            DFATransition(3, 16, 16),
            DFATransition(3, 17, 16),
            DFATransition(3, 18, 16),
            DFATransition(3, 19, 16),
            DFATransition(3, 20, 16),
            DFATransition(3, 21, 16),
            DFATransition(3, 22, 16),
            DFATransition(3, 23, 16),
            DFATransition(3, 24, 16),
            DFATransition(3, 25, 16),
            DFATransition(3, 31, 16),
            DFATransition(3, 32, 16),
            DFATransition(3, 33, 16),
            DFATransition(3, 34, 16),
            DFATransition(3, 35, 16),
            DFATransition(3, 36, 16),
            DFATransition(3, 37, 16),
            DFATransition(3, 38, 16),
            DFATransition(3, 39, 16),
            DFATransition(3, 41, 16),
            DFATransition(3, 42, 16),
            DFATransition(3, 43, 16),
            DFATransition(3, 44, 2),
            DFATransition(4, 9, 5),
            DFATransition(4, 12, 5),
            DFATransition(4, 31, 5),
            DFATransition(4, 32, 5),
            DFATransition(4, 33, 5),
            DFATransition(4, 34, 5),
            DFATransition(4, 35, 5),
            DFATransition(4, 36, 5),
            DFATransition(4, 37, 5),
            DFATransition(4, 39, 5),
            DFATransition(4, 41, 5),
            DFATransition(4, 42, 5),
            DFATransition(4, 43, 5),
            DFATransition(6, 6, 16),
            DFATransition(6, 7, 16),
            DFATransition(6, 8, 16),
            DFATransition(6, 9, 16),
            DFATransition(6, 12, 16),
            DFATransition(6, 13, 16),
            DFATransition(6, 14, 16),
            DFATransition(6, 15, 16),
            DFATransition(6, 16, 16),
            DFATransition(6, 17, 16),
            DFATransition(6, 18, 16),
            DFATransition(6, 19, 16),
            DFATransition(6, 20, 16),
            DFATransition(6, 21, 16),
            DFATransition(6, 22, 16),
            DFATransition(6, 23, 16),
            DFATransition(6, 24, 16),
            DFATransition(6, 25, 16),
            DFATransition(6, 31, 16),
            DFATransition(6, 32, 16),
            DFATransition(6, 33, 16),
            DFATransition(6, 34, 16),
            DFATransition(6, 35, 16),
            DFATransition(6, 36, 16),
            DFATransition(6, 37, 16),
            DFATransition(6, 38, 16),
            DFATransition(6, 39, 16),
            DFATransition(6, 41, 16),
            DFATransition(6, 42, 16),
            DFATransition(6, 43, 16),
            DFATransition(7, 6, 16),
            DFATransition(7, 7, 16),
            DFATransition(7, 8, 16),
            DFATransition(7, 9, 16),
            DFATransition(7, 12, 16),
            DFATransition(7, 13, 16),
            DFATransition(7, 14, 16),
            DFATransition(7, 15, 16),
            DFATransition(7, 16, 16),
            DFATransition(7, 17, 16),
            DFATransition(7, 18, 16),
            DFATransition(7, 19, 16),
            DFATransition(7, 20, 16),
            DFATransition(7, 21, 16),
            DFATransition(7, 22, 16),
            DFATransition(7, 23, 16),
            DFATransition(7, 24, 16),
            DFATransition(7, 25, 16),
            DFATransition(7, 31, 16),
            DFATransition(7, 32, 16),
            DFATransition(7, 33, 16),
            DFATransition(7, 34, 16),
            DFATransition(7, 35, 16),
            DFATransition(7, 36, 16),
            DFATransition(7, 37, 16),
            DFATransition(7, 38, 16),
            DFATransition(7, 39, 16),
            DFATransition(7, 41, 16),
            DFATransition(7, 42, 16),
            DFATransition(7, 43, 16),
            DFATransition(8, 6, 16),
            DFATransition(8, 7, 16),
            DFATransition(8, 8, 16),
            DFATransition(8, 9, 16),
            DFATransition(8, 12, 16),
            DFATransition(8, 13, 16),
            DFATransition(8, 14, 16),
            DFATransition(8, 15, 16),
            DFATransition(8, 16, 16),
            DFATransition(8, 17, 16),
            DFATransition(8, 18, 16),
            DFATransition(8, 19, 16),
            DFATransition(8, 20, 16),
            DFATransition(8, 21, 16),
            DFATransition(8, 22, 16),
            DFATransition(8, 23, 16),
            DFATransition(8, 24, 16),
            DFATransition(8, 25, 16),
            DFATransition(8, 31, 16),
            DFATransition(8, 32, 16),
            DFATransition(8, 33, 16),
            DFATransition(8, 34, 16),
            DFATransition(8, 35, 16),
            DFATransition(8, 36, 16),
            DFATransition(8, 37, 16),
            DFATransition(8, 38, 16),
            DFATransition(8, 39, 16),
            DFATransition(8, 41, 16),
            DFATransition(8, 42, 16),
            DFATransition(8, 43, 16),
            DFATransition(9, 6, 16),
            DFATransition(9, 7, 16),
            DFATransition(9, 8, 16),
            DFATransition(9, 9, 16),
            DFATransition(9, 12, 16),
            DFATransition(9, 13, 16),
            DFATransition(9, 14, 16),
            DFATransition(9, 15, 16),
            DFATransition(9, 16, 16),
            DFATransition(9, 17, 16),
            DFATransition(9, 18, 16),
            DFATransition(9, 19, 16),
            DFATransition(9, 20, 16),
            DFATransition(9, 21, 16),
            DFATransition(9, 22, 16),
            DFATransition(9, 23, 16),
            DFATransition(9, 24, 16),
            DFATransition(9, 25, 16),
            DFATransition(9, 31, 16),
            DFATransition(9, 32, 16),
            DFATransition(9, 33, 16),
            DFATransition(9, 34, 16),
            DFATransition(9, 35, 16),
            DFATransition(9, 36, 16),
            DFATransition(9, 37, 16),
            DFATransition(9, 38, 16),
            DFATransition(9, 39, 16),
            DFATransition(9, 41, 16),
            DFATransition(9, 42, 16),
            DFATransition(9, 43, 16),
            DFATransition(10, 6, 16),
            DFATransition(10, 7, 16),
            DFATransition(10, 8, 16),
            DFATransition(10, 9, 16),
            DFATransition(10, 12, 16),
            DFATransition(10, 13, 16),
            DFATransition(10, 14, 16),
            DFATransition(10, 15, 16),
            DFATransition(10, 16, 16),
            DFATransition(10, 17, 16),
            DFATransition(10, 18, 16),
            DFATransition(10, 19, 16),
            DFATransition(10, 20, 16),
            DFATransition(10, 21, 16),
            DFATransition(10, 22, 16),
            DFATransition(10, 23, 16),
            DFATransition(10, 24, 16),
            DFATransition(10, 25, 16),
            DFATransition(10, 31, 16),
            DFATransition(10, 32, 16),
            DFATransition(10, 33, 16),
            DFATransition(10, 34, 16),
            DFATransition(10, 35, 16),
            DFATransition(10, 36, 16),
            DFATransition(10, 37, 16),
            DFATransition(10, 38, 16),
            DFATransition(10, 39, 16),
            DFATransition(10, 41, 16),
            DFATransition(10, 42, 16),
            DFATransition(10, 43, 16),
            DFATransition(11, 9, 16),
            DFATransition(11, 12, 16),
            DFATransition(11, 31, 16),
            DFATransition(11, 32, 16),
            DFATransition(11, 33, 16),
            DFATransition(11, 34, 16),
            DFATransition(11, 35, 16),
            DFATransition(11, 36, 16),
            DFATransition(11, 37, 16),
            DFATransition(11, 38, 16),
            DFATransition(11, 39, 16),
            DFATransition(11, 41, 16),
            DFATransition(11, 42, 16),
            DFATransition(11, 43, 16),
            DFATransition(12, 9, 16),
            DFATransition(12, 12, 16),
            DFATransition(12, 31, 16),
            DFATransition(12, 32, 16),
            DFATransition(12, 33, 16),
            DFATransition(12, 34, 16),
            DFATransition(12, 35, 16),
            DFATransition(12, 36, 16),
            DFATransition(12, 37, 16),
            DFATransition(12, 39, 16),
            DFATransition(12, 41, 16),
            DFATransition(12, 42, 16),
            DFATransition(12, 43, 16),
            DFATransition(13, 37, 16),
            DFATransition(14, 9, 16),
            DFATransition(14, 12, 16),
            DFATransition(14, 31, 16),
            DFATransition(14, 32, 16),
            DFATransition(14, 33, 16),
            DFATransition(14, 34, 16),
            DFATransition(14, 35, 16),
            DFATransition(14, 36, 16),
            DFATransition(14, 37, 16),
            DFATransition(14, 39, 16),
            DFATransition(14, 41, 16),
            DFATransition(14, 42, 16),
            DFATransition(14, 43, 16),
            DFATransition(15, 6, 16),
            DFATransition(15, 7, 16),
            DFATransition(15, 8, 16),
            DFATransition(15, 9, 16),
            DFATransition(15, 12, 16),
            DFATransition(15, 13, 16),
            DFATransition(15, 14, 16),
            DFATransition(15, 15, 16),
            DFATransition(15, 16, 16),
            DFATransition(15, 17, 16),
            DFATransition(15, 18, 16),
            DFATransition(15, 19, 16),
            DFATransition(15, 20, 16),
            DFATransition(15, 21, 16),
            DFATransition(15, 22, 16),
            DFATransition(15, 23, 16),
            DFATransition(15, 24, 16),
            DFATransition(15, 25, 16),
            DFATransition(15, 31, 16),
            DFATransition(15, 32, 16),
            DFATransition(15, 33, 16),
            DFATransition(15, 34, 16),
            DFATransition(15, 35, 16),
            DFATransition(15, 36, 16),
            DFATransition(15, 37, 16),
            DFATransition(15, 38, 16),
            DFATransition(15, 39, 16),
            DFATransition(15, 41, 16),
            DFATransition(15, 42, 16),
            DFATransition(15, 43, 16),
        ],
        k: 2,
    },
    /* 19 - "Expr0" */
    LookaheadDFA {
        states: &[
            None,
            Some(78),
            Some(79),
            Some(80),
            Some(81),
            Some(82),
            Some(83),
            Some(84),
            Some(85),
            Some(86),
            Some(87),
            Some(88),
        ],
        transitions: &[
            DFATransition(0, 9, 7),
            DFATransition(0, 31, 2),
            DFATransition(0, 32, 2),
            DFATransition(0, 33, 1),
            DFATransition(0, 34, 3),
            DFATransition(0, 35, 4),
            DFATransition(0, 36, 5),
            DFATransition(0, 37, 6),
            DFATransition(0, 39, 8),
            DFATransition(0, 41, 9),
            DFATransition(0, 42, 10),
            DFATransition(0, 43, 11),
        ],
        k: 1,
    },
    /* 20 - "Expr1" */
    LookaheadDFA {
        states: &[Some(56)],
        transitions: &[],
        k: 0,
    },
    /* 21 - "Expr1List" */
    LookaheadDFA {
        states: &[None, Some(57), Some(60)],
        transitions: &[
            DFATransition(0, 6, 1),
            DFATransition(0, 7, 2),
            DFATransition(0, 8, 2),
            DFATransition(0, 9, 2),
            DFATransition(0, 12, 2),
            DFATransition(0, 13, 2),
            DFATransition(0, 14, 2),
            DFATransition(0, 15, 2),
            DFATransition(0, 16, 2),
            DFATransition(0, 17, 2),
            DFATransition(0, 18, 2),
            DFATransition(0, 19, 2),
            DFATransition(0, 20, 2),
            DFATransition(0, 21, 2),
            DFATransition(0, 22, 2),
            DFATransition(0, 23, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 1),
            DFATransition(0, 31, 2),
            DFATransition(0, 32, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
            DFATransition(0, 36, 2),
            DFATransition(0, 37, 2),
            DFATransition(0, 38, 2),
            DFATransition(0, 39, 2),
            DFATransition(0, 41, 2),
            DFATransition(0, 42, 2),
            DFATransition(0, 43, 2),
        ],
        k: 1,
    },
    /* 22 - "Expr1ListGroup" */
    LookaheadDFA {
        states: &[None, Some(58), Some(59)],
        transitions: &[DFATransition(0, 6, 2), DFATransition(0, 25, 1)],
        k: 1,
    },
    /* 23 - "Expr2" */
    LookaheadDFA {
        states: &[Some(51)],
        transitions: &[],
        k: 0,
    },
    /* 24 - "Expr2List" */
    LookaheadDFA {
        states: &[None, Some(52), Some(55)],
        transitions: &[
            DFATransition(0, 7, 2),
            DFATransition(0, 8, 2),
            DFATransition(0, 9, 2),
            DFATransition(0, 12, 2),
            DFATransition(0, 13, 2),
            DFATransition(0, 14, 2),
            DFATransition(0, 15, 2),
            DFATransition(0, 16, 2),
            DFATransition(0, 17, 2),
            DFATransition(0, 18, 2),
            DFATransition(0, 19, 2),
            DFATransition(0, 20, 2),
            DFATransition(0, 21, 2),
            DFATransition(0, 22, 2),
            DFATransition(0, 23, 1),
            DFATransition(0, 24, 1),
            DFATransition(0, 31, 2),
            DFATransition(0, 32, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
            DFATransition(0, 36, 2),
            DFATransition(0, 37, 2),
            DFATransition(0, 38, 2),
            DFATransition(0, 39, 2),
            DFATransition(0, 41, 2),
            DFATransition(0, 42, 2),
            DFATransition(0, 43, 2),
        ],
        k: 1,
    },
    /* 25 - "Expr2ListGroup" */
    LookaheadDFA {
        states: &[None, Some(53), Some(54)],
        transitions: &[DFATransition(0, 23, 1), DFATransition(0, 24, 2)],
        k: 1,
    },
    /* 26 - "Expr3" */
    LookaheadDFA {
        states: &[Some(46)],
        transitions: &[],
        k: 0,
    },
    /* 27 - "Expr3List" */
    LookaheadDFA {
        states: &[None, Some(47), Some(50)],
        transitions: &[
            DFATransition(0, 7, 2),
            DFATransition(0, 8, 2),
            DFATransition(0, 9, 2),
            DFATransition(0, 12, 2),
            DFATransition(0, 13, 2),
            DFATransition(0, 14, 2),
            DFATransition(0, 15, 2),
            DFATransition(0, 16, 2),
            DFATransition(0, 17, 2),
            DFATransition(0, 18, 2),
            DFATransition(0, 19, 2),
            DFATransition(0, 20, 2),
            DFATransition(0, 21, 1),
            DFATransition(0, 22, 1),
            DFATransition(0, 31, 2),
            DFATransition(0, 32, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
            DFATransition(0, 36, 2),
            DFATransition(0, 37, 2),
            DFATransition(0, 38, 2),
            DFATransition(0, 39, 2),
            DFATransition(0, 41, 2),
            DFATransition(0, 42, 2),
            DFATransition(0, 43, 2),
        ],
        k: 1,
    },
    /* 28 - "Expr3ListGroup" */
    LookaheadDFA {
        states: &[None, Some(48), Some(49)],
        transitions: &[DFATransition(0, 21, 1), DFATransition(0, 22, 2)],
        k: 1,
    },
    /* 29 - "Expr4" */
    LookaheadDFA {
        states: &[Some(40)],
        transitions: &[],
        k: 0,
    },
    /* 30 - "Expr4List" */
    LookaheadDFA {
        states: &[None, Some(41), Some(45)],
        transitions: &[
            DFATransition(0, 7, 2),
            DFATransition(0, 8, 2),
            DFATransition(0, 9, 2),
            DFATransition(0, 12, 2),
            DFATransition(0, 13, 2),
            DFATransition(0, 14, 2),
            DFATransition(0, 15, 2),
            DFATransition(0, 16, 2),
            DFATransition(0, 17, 2),
            DFATransition(0, 18, 1),
            DFATransition(0, 19, 1),
            DFATransition(0, 20, 1),
            DFATransition(0, 31, 2),
            DFATransition(0, 32, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
            DFATransition(0, 36, 2),
            DFATransition(0, 37, 2),
            DFATransition(0, 38, 2),
            DFATransition(0, 39, 2),
            DFATransition(0, 41, 2),
            DFATransition(0, 42, 2),
            DFATransition(0, 43, 2),
        ],
        k: 1,
    },
    /* 31 - "Expr4ListGroup" */
    LookaheadDFA {
        states: &[None, Some(42), Some(43), Some(44)],
        transitions: &[
            DFATransition(0, 18, 1),
            DFATransition(0, 19, 2),
            DFATransition(0, 20, 3),
        ],
        k: 1,
    },
    /* 32 - "Expr5" */
    LookaheadDFA {
        states: &[Some(32)],
        transitions: &[],
        k: 0,
    },
    /* 33 - "Expr5List" */
    LookaheadDFA {
        states: &[None, Some(33), Some(39)],
        transitions: &[
            DFATransition(0, 7, 2),
            DFATransition(0, 8, 2),
            DFATransition(0, 9, 2),
            DFATransition(0, 12, 2),
            DFATransition(0, 13, 1),
            DFATransition(0, 14, 1),
            DFATransition(0, 15, 1),
            DFATransition(0, 16, 1),
            DFATransition(0, 17, 1),
            DFATransition(0, 31, 2),
            DFATransition(0, 32, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
            DFATransition(0, 36, 2),
            DFATransition(0, 37, 2),
            DFATransition(0, 38, 2),
            DFATransition(0, 39, 2),
            DFATransition(0, 41, 2),
            DFATransition(0, 42, 2),
            DFATransition(0, 43, 2),
        ],
        k: 1,
    },
    /* 34 - "Expr5ListGroup" */
    LookaheadDFA {
        states: &[None, Some(34), Some(35), Some(36), Some(37), Some(38)],
        transitions: &[
            DFATransition(0, 13, 1),
            DFATransition(0, 14, 2),
            DFATransition(0, 15, 3),
            DFATransition(0, 16, 4),
            DFATransition(0, 17, 5),
        ],
        k: 1,
    },
    /* 35 - "Field" */
    LookaheadDFA {
        states: &[Some(13)],
        transitions: &[],
        k: 0,
    },
    /* 36 - "FieldList" */
    LookaheadDFA {
        states: &[Some(6)],
        transitions: &[],
        k: 0,
    },
    /* 37 - "FieldListList" */
    LookaheadDFA {
        states: &[None, Some(9), Some(10)],
        transitions: &[
            DFATransition(0, 7, 2),
            DFATransition(0, 8, 1),
            DFATransition(0, 9, 1),
            DFATransition(0, 33, 1),
        ],
        k: 1,
    },
    /* 38 - "FieldListOpt" */
    LookaheadDFA {
        states: &[None, Some(11), Some(12)],
        transitions: &[
            DFATransition(0, 8, 1),
            DFATransition(0, 9, 2),
            DFATransition(0, 33, 2),
        ],
        k: 1,
    },
    /* 39 - "FieldListSuffix" */
    LookaheadDFA {
        states: &[None, Some(7), Some(8)],
        transitions: &[
            DFATransition(0, 7, 1),
            DFATransition(0, 9, 2),
            DFATransition(0, 33, 2),
        ],
        k: 1,
    },
    /* 40 - "FieldOpt" */
    LookaheadDFA {
        states: &[None, Some(14), Some(15)],
        transitions: &[DFATransition(0, 9, 1), DFATransition(0, 33, 2)],
        k: 1,
    },
    /* 41 - "FloatLiteral" */
    LookaheadDFA {
        states: &[Some(92)],
        transitions: &[],
        k: 0,
    },
    /* 42 - "Function" */
    LookaheadDFA {
        states: &[Some(17)],
        transitions: &[],
        k: 0,
    },
    /* 43 - "FunctionBody" */
    LookaheadDFA {
        states: &[Some(26)],
        transitions: &[],
        k: 0,
    },
    /* 44 - "FunctionOpt" */
    LookaheadDFA {
        states: &[None, Some(18), Some(19)],
        transitions: &[DFATransition(0, 10, 2), DFATransition(0, 11, 1)],
        k: 1,
    },
    /* 45 - "Identifier" */
    LookaheadDFA {
        states: &[Some(91)],
        transitions: &[],
        k: 0,
    },
    /* 46 - "IfExpr" */
    LookaheadDFA {
        states: &[Some(101)],
        transitions: &[],
        k: 0,
    },
    /* 47 - "IfExprOpt" */
    LookaheadDFA {
        states: &[None, Some(102), Some(103)],
        transitions: &[
            DFATransition(0, 6, 2),
            DFATransition(0, 7, 2),
            DFATransition(0, 8, 2),
            DFATransition(0, 9, 2),
            DFATransition(0, 12, 2),
            DFATransition(0, 13, 2),
            DFATransition(0, 14, 2),
            DFATransition(0, 15, 2),
            DFATransition(0, 16, 2),
            DFATransition(0, 17, 2),
            DFATransition(0, 18, 2),
            DFATransition(0, 19, 2),
            DFATransition(0, 20, 2),
            DFATransition(0, 21, 2),
            DFATransition(0, 22, 2),
            DFATransition(0, 23, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
            DFATransition(0, 31, 2),
            DFATransition(0, 32, 2),
            DFATransition(0, 33, 2),
            DFATransition(0, 34, 2),
            DFATransition(0, 35, 2),
            DFATransition(0, 36, 2),
            DFATransition(0, 37, 2),
            DFATransition(0, 38, 2),
            DFATransition(0, 39, 2),
            DFATransition(0, 40, 1),
            DFATransition(0, 41, 2),
            DFATransition(0, 42, 2),
            DFATransition(0, 43, 2),
        ],
        k: 1,
    },
    /* 48 - "IntegerLiteral" */
    LookaheadDFA {
        states: &[Some(93)],
        transitions: &[],
        k: 0,
    },
    /* 49 - "Item" */
    LookaheadDFA {
        states: &[None, Some(3), Some(4)],
        transitions: &[
            DFATransition(0, 5, 1),
            DFATransition(0, 10, 2),
            DFATransition(0, 11, 2),
        ],
        k: 1,
    },
    /* 50 - "Items" */
    LookaheadDFA {
        states: &[Some(0)],
        transitions: &[],
        k: 0,
    },
    /* 51 - "ItemsList" */
    LookaheadDFA {
        states: &[None, Some(1), Some(2)],
        transitions: &[
            DFATransition(0, 0, 2),
            DFATransition(0, 5, 1),
            DFATransition(0, 10, 1),
            DFATransition(0, 11, 1),
        ],
        k: 1,
    },
    /* 52 - "LocalVariable" */
    LookaheadDFA {
        states: &[Some(108)],
        transitions: &[],
        k: 0,
    },
    /* 53 - "LocalVariableOpt" */
    LookaheadDFA {
        states: &[None, Some(109), Some(110)],
        transitions: &[DFATransition(0, 9, 1), DFATransition(0, 33, 2)],
        k: 1,
    },
    /* 54 - "Loop" */
    LookaheadDFA {
        states: &[Some(105)],
        transitions: &[],
        k: 0,
    },
    /* 55 - "MaybeTrailingComma" */
    LookaheadDFA {
        states: &[Some(72)],
        transitions: &[],
        k: 0,
    },
    /* 56 - "MaybeTrailingCommaOpt" */
    LookaheadDFA {
        states: &[None, Some(73), Some(74)],
        transitions: &[DFATransition(0, 7, 2), DFATransition(0, 8, 1)],
        k: 1,
    },
    /* 57 - "ReturnWithExpr" */
    LookaheadDFA {
        states: &[Some(30)],
        transitions: &[],
        k: 0,
    },
    /* 58 - "ReturnWithoutExpr" */
    LookaheadDFA {
        states: &[Some(31)],
        transitions: &[],
        k: 0,
    },
    /* 59 - "StorageMode" */
    LookaheadDFA {
        states: &[Some(16)],
        transitions: &[],
        k: 0,
    },
    /* 60 - "StringLiteral" */
    LookaheadDFA {
        states: &[Some(94)],
        transitions: &[],
        k: 0,
    },
    /* 61 - "Tuple" */
    LookaheadDFA {
        states: &[Some(107)],
        transitions: &[],
        k: 0,
    },
    /* 62 - "While" */
    LookaheadDFA {
        states: &[Some(106)],
        transitions: &[],
        k: 0,
    },
];

pub const PRODUCTIONS: &[Production; 111] = &[
    // 0 - Items: ItemsList /* Vec */;
    Production {
        lhs: 50,
        production: &[ParseType::N(51)],
    },
    // 1 - ItemsList: Item ItemsList;
    Production {
        lhs: 51,
        production: &[ParseType::N(51), ParseType::N(49)],
    },
    // 2 - ItemsList: ;
    Production {
        lhs: 51,
        production: &[],
    },
    // 3 - Item: Class;
    Production {
        lhs: 49,
        production: &[ParseType::N(13)],
    },
    // 4 - Item: Function;
    Production {
        lhs: 49,
        production: &[ParseType::N(42)],
    },
    // 5 - Class: "class" Identifier FieldList;
    Production {
        lhs: 13,
        production: &[ParseType::N(36), ParseType::N(45), ParseType::T(5)],
    },
    // 6 - FieldList: "\(" FieldListSuffix;
    Production {
        lhs: 36,
        production: &[ParseType::N(39), ParseType::T(6)],
    },
    // 7 - FieldListSuffix: "\)";
    Production {
        lhs: 39,
        production: &[ParseType::T(7)],
    },
    // 8 - FieldListSuffix: Field FieldListList /* Vec */ "\)";
    Production {
        lhs: 39,
        production: &[ParseType::T(7), ParseType::N(37), ParseType::N(35)],
    },
    // 9 - FieldListList: FieldListOpt /* Option */ Field FieldListList;
    Production {
        lhs: 37,
        production: &[ParseType::N(37), ParseType::N(35), ParseType::N(38)],
    },
    // 10 - FieldListList: ;
    Production {
        lhs: 37,
        production: &[],
    },
    // 11 - FieldListOpt: ",";
    Production {
        lhs: 38,
        production: &[ParseType::T(8)],
    },
    // 12 - FieldListOpt: ;
    Production {
        lhs: 38,
        production: &[],
    },
    // 13 - Field: FieldOpt /* Option */ Identifier;
    Production {
        lhs: 35,
        production: &[ParseType::N(45), ParseType::N(40)],
    },
    // 14 - FieldOpt: StorageMode;
    Production {
        lhs: 40,
        production: &[ParseType::N(59)],
    },
    // 15 - FieldOpt: ;
    Production {
        lhs: 40,
        production: &[],
    },
    // 16 - StorageMode: "atomic";
    Production {
        lhs: 59,
        production: &[ParseType::T(9)],
    },
    // 17 - Function: FunctionOpt /* Option */ "fn" Identifier ArgumentList FunctionBody;
    Production {
        lhs: 42,
        production: &[
            ParseType::N(43),
            ParseType::N(0),
            ParseType::N(45),
            ParseType::T(10),
            ParseType::N(44),
        ],
    },
    // 18 - FunctionOpt: Effect;
    Production {
        lhs: 44,
        production: &[ParseType::N(17)],
    },
    // 19 - FunctionOpt: ;
    Production {
        lhs: 44,
        production: &[],
    },
    // 20 - Effect: "async";
    Production {
        lhs: 17,
        production: &[ParseType::T(11)],
    },
    // 21 - ArgumentList: "\(" ArgumentListSuffix;
    Production {
        lhs: 0,
        production: &[ParseType::N(2), ParseType::T(6)],
    },
    // 22 - ArgumentListSuffix: "\)";
    Production {
        lhs: 2,
        production: &[ParseType::T(7)],
    },
    // 23 - ArgumentListSuffix: Identifier ArgumentListList /* Vec */ "\)";
    Production {
        lhs: 2,
        production: &[ParseType::T(7), ParseType::N(1), ParseType::N(45)],
    },
    // 24 - ArgumentListList: "," Identifier ArgumentListList;
    Production {
        lhs: 1,
        production: &[ParseType::N(1), ParseType::N(45), ParseType::T(8)],
    },
    // 25 - ArgumentListList: ;
    Production {
        lhs: 1,
        production: &[],
    },
    // 26 - FunctionBody: BlockExpr;
    Production {
        lhs: 43,
        production: &[ParseType::N(4)],
    },
    // 27 - Expr: LocalVariable;
    Production {
        lhs: 18,
        production: &[ParseType::N(52)],
    },
    // 28 - Expr: ReturnWithExpr;
    Production {
        lhs: 18,
        production: &[ParseType::N(57)],
    },
    // 29 - Expr: Expr5;
    Production {
        lhs: 18,
        production: &[ParseType::N(32)],
    },
    // 30 - ReturnWithExpr: "return" Expr;
    Production {
        lhs: 57,
        production: &[ParseType::N(18), ParseType::T(12)],
    },
    // 31 - ReturnWithoutExpr: "return";
    Production {
        lhs: 58,
        production: &[ParseType::T(12)],
    },
    // 32 - Expr5: Expr4 Expr5List /* Vec */;
    Production {
        lhs: 32,
        production: &[ParseType::N(33), ParseType::N(29)],
    },
    // 33 - Expr5List: Expr5ListGroup Expr4 Expr5List;
    Production {
        lhs: 33,
        production: &[ParseType::N(33), ParseType::N(29), ParseType::N(34)],
    },
    // 34 - Expr5ListGroup: "\+=";
    Production {
        lhs: 34,
        production: &[ParseType::T(13)],
    },
    // 35 - Expr5ListGroup: "-=";
    Production {
        lhs: 34,
        production: &[ParseType::T(14)],
    },
    // 36 - Expr5ListGroup: "/=";
    Production {
        lhs: 34,
        production: &[ParseType::T(15)],
    },
    // 37 - Expr5ListGroup: "\*=";
    Production {
        lhs: 34,
        production: &[ParseType::T(16)],
    },
    // 38 - Expr5ListGroup: ":=";
    Production {
        lhs: 34,
        production: &[ParseType::T(17)],
    },
    // 39 - Expr5List: ;
    Production {
        lhs: 33,
        production: &[],
    },
    // 40 - Expr4: Expr3 Expr4List /* Vec */;
    Production {
        lhs: 29,
        production: &[ParseType::N(30), ParseType::N(26)],
    },
    // 41 - Expr4List: Expr4ListGroup Expr3 Expr4List;
    Production {
        lhs: 30,
        production: &[ParseType::N(30), ParseType::N(26), ParseType::N(31)],
    },
    // 42 - Expr4ListGroup: "==";
    Production {
        lhs: 31,
        production: &[ParseType::T(18)],
    },
    // 43 - Expr4ListGroup: "<";
    Production {
        lhs: 31,
        production: &[ParseType::T(19)],
    },
    // 44 - Expr4ListGroup: ">";
    Production {
        lhs: 31,
        production: &[ParseType::T(20)],
    },
    // 45 - Expr4List: ;
    Production {
        lhs: 30,
        production: &[],
    },
    // 46 - Expr3: Expr2 Expr3List /* Vec */;
    Production {
        lhs: 26,
        production: &[ParseType::N(27), ParseType::N(23)],
    },
    // 47 - Expr3List: Expr3ListGroup Expr2 Expr3List;
    Production {
        lhs: 27,
        production: &[ParseType::N(27), ParseType::N(23), ParseType::N(28)],
    },
    // 48 - Expr3ListGroup: "\+";
    Production {
        lhs: 28,
        production: &[ParseType::T(21)],
    },
    // 49 - Expr3ListGroup: "-";
    Production {
        lhs: 28,
        production: &[ParseType::T(22)],
    },
    // 50 - Expr3List: ;
    Production {
        lhs: 27,
        production: &[],
    },
    // 51 - Expr2: Expr1 Expr2List /* Vec */;
    Production {
        lhs: 23,
        production: &[ParseType::N(24), ParseType::N(20)],
    },
    // 52 - Expr2List: Expr2ListGroup Expr1 Expr2List;
    Production {
        lhs: 24,
        production: &[ParseType::N(24), ParseType::N(20), ParseType::N(25)],
    },
    // 53 - Expr2ListGroup: "/";
    Production {
        lhs: 25,
        production: &[ParseType::T(23)],
    },
    // 54 - Expr2ListGroup: "\*";
    Production {
        lhs: 25,
        production: &[ParseType::T(24)],
    },
    // 55 - Expr2List: ;
    Production {
        lhs: 24,
        production: &[],
    },
    // 56 - Expr1: Expr0 Expr1List /* Vec */;
    Production {
        lhs: 20,
        production: &[ParseType::N(21), ParseType::N(19)],
    },
    // 57 - Expr1List: Expr1ListGroup Expr1List;
    Production {
        lhs: 21,
        production: &[ParseType::N(21), ParseType::N(22)],
    },
    // 58 - Expr1ListGroup: DotExpr;
    Production {
        lhs: 22,
        production: &[ParseType::N(15)],
    },
    // 59 - Expr1ListGroup: CallArgumentList;
    Production {
        lhs: 22,
        production: &[ParseType::N(9)],
    },
    // 60 - Expr1List: ;
    Production {
        lhs: 21,
        production: &[],
    },
    // 61 - DotExpr: "\." DotSuffix;
    Production {
        lhs: 15,
        production: &[ParseType::N(16), ParseType::T(25)],
    },
    // 62 - DotSuffix: "await";
    Production {
        lhs: 16,
        production: &[ParseType::T(26)],
    },
    // 63 - DotSuffix: "share";
    Production {
        lhs: 16,
        production: &[ParseType::T(27)],
    },
    // 64 - DotSuffix: "give";
    Production {
        lhs: 16,
        production: &[ParseType::T(28)],
    },
    // 65 - DotSuffix: "lease";
    Production {
        lhs: 16,
        production: &[ParseType::T(29)],
    },
    // 66 - DotSuffix: Identifier;
    Production {
        lhs: 16,
        production: &[ParseType::N(45)],
    },
    // 67 - CallArgumentList: "\(" CallArgumentListSuffix;
    Production {
        lhs: 9,
        production: &[ParseType::N(11), ParseType::T(6)],
    },
    // 68 - CallArgumentListSuffix: "\)";
    Production {
        lhs: 11,
        production: &[ParseType::T(7)],
    },
    // 69 - CallArgumentListSuffix: CallArgument CallArgumentListList /* Vec */ MaybeTrailingComma "\)";
    Production {
        lhs: 11,
        production: &[
            ParseType::T(7),
            ParseType::N(55),
            ParseType::N(10),
            ParseType::N(8),
        ],
    },
    // 70 - CallArgumentListList: "," CallArgument CallArgumentListList;
    Production {
        lhs: 10,
        production: &[ParseType::N(10), ParseType::N(8), ParseType::T(8)],
    },
    // 71 - CallArgumentListList: ;
    Production {
        lhs: 10,
        production: &[],
    },
    // 72 - MaybeTrailingComma: MaybeTrailingCommaOpt /* Option */;
    Production {
        lhs: 55,
        production: &[ParseType::N(56)],
    },
    // 73 - MaybeTrailingCommaOpt: ",";
    Production {
        lhs: 56,
        production: &[ParseType::T(8)],
    },
    // 74 - MaybeTrailingCommaOpt: ;
    Production {
        lhs: 56,
        production: &[],
    },
    // 75 - CallArgument: CallArgumentOpt /* Option */ Expr;
    Production {
        lhs: 8,
        production: &[ParseType::N(18), ParseType::N(12)],
    },
    // 76 - CallArgumentOpt: Identifier ":";
    Production {
        lhs: 12,
        production: &[ParseType::T(30), ParseType::N(45)],
    },
    // 77 - CallArgumentOpt: ;
    Production {
        lhs: 12,
        production: &[],
    },
    // 78 - Expr0: Identifier;
    Production {
        lhs: 19,
        production: &[ParseType::N(45)],
    },
    // 79 - Expr0: BooleanLiteral;
    Production {
        lhs: 19,
        production: &[ParseType::N(7)],
    },
    // 80 - Expr0: FloatLiteral;
    Production {
        lhs: 19,
        production: &[ParseType::N(41)],
    },
    // 81 - Expr0: IntegerLiteral;
    Production {
        lhs: 19,
        production: &[ParseType::N(48)],
    },
    // 82 - Expr0: StringLiteral;
    Production {
        lhs: 19,
        production: &[ParseType::N(60)],
    },
    // 83 - Expr0: BlockExpr;
    Production {
        lhs: 19,
        production: &[ParseType::N(4)],
    },
    // 84 - Expr0: AtomicBlock;
    Production {
        lhs: 19,
        production: &[ParseType::N(3)],
    },
    // 85 - Expr0: IfExpr;
    Production {
        lhs: 19,
        production: &[ParseType::N(46)],
    },
    // 86 - Expr0: Loop;
    Production {
        lhs: 19,
        production: &[ParseType::N(54)],
    },
    // 87 - Expr0: While;
    Production {
        lhs: 19,
        production: &[ParseType::N(62)],
    },
    // 88 - Expr0: Tuple;
    Production {
        lhs: 19,
        production: &[ParseType::N(61)],
    },
    // 89 - BooleanLiteral: "true";
    Production {
        lhs: 7,
        production: &[ParseType::T(31)],
    },
    // 90 - BooleanLiteral: "false";
    Production {
        lhs: 7,
        production: &[ParseType::T(32)],
    },
    // 91 - Identifier: "[a-z|A-Z_][a-z|A-Z|0-9_]*";
    Production {
        lhs: 45,
        production: &[ParseType::T(33)],
    },
    // 92 - FloatLiteral: "[0-9][0-9_]*\.[0-9][0-9_]*";
    Production {
        lhs: 41,
        production: &[ParseType::T(34)],
    },
    // 93 - IntegerLiteral: "[0-9][0-9_]*";
    Production {
        lhs: 48,
        production: &[ParseType::T(35)],
    },
    // 94 - StringLiteral: "\u{0022}(?s:[^\u{0022}]*)\u{0022}";
    Production {
        lhs: 60,
        production: &[ParseType::T(36)],
    },
    // 95 - BlockExpr: "\{" BlockExprList /* Vec */ BlockExprOpt /* Option */ "\}";
    Production {
        lhs: 4,
        production: &[
            ParseType::T(38),
            ParseType::N(6),
            ParseType::N(5),
            ParseType::T(37),
        ],
    },
    // 96 - BlockExprList: Expr BlockExprList;
    Production {
        lhs: 5,
        production: &[ParseType::N(5), ParseType::N(18)],
    },
    // 97 - BlockExprList: ;
    Production {
        lhs: 5,
        production: &[],
    },
    // 98 - BlockExprOpt: ReturnWithoutExpr;
    Production {
        lhs: 6,
        production: &[ParseType::N(58)],
    },
    // 99 - BlockExprOpt: ;
    Production {
        lhs: 6,
        production: &[],
    },
    // 100 - AtomicBlock: "atomic" BlockExpr;
    Production {
        lhs: 3,
        production: &[ParseType::N(4), ParseType::T(9)],
    },
    // 101 - IfExpr: "if" Condition BlockExpr IfExprOpt /* Option */;
    Production {
        lhs: 46,
        production: &[
            ParseType::N(47),
            ParseType::N(4),
            ParseType::N(14),
            ParseType::T(39),
        ],
    },
    // 102 - IfExprOpt: "else" BlockExpr;
    Production {
        lhs: 47,
        production: &[ParseType::N(4), ParseType::T(40)],
    },
    // 103 - IfExprOpt: ;
    Production {
        lhs: 47,
        production: &[],
    },
    // 104 - Condition: Expr;
    Production {
        lhs: 14,
        production: &[ParseType::N(18)],
    },
    // 105 - Loop: "loop" BlockExpr;
    Production {
        lhs: 54,
        production: &[ParseType::N(4), ParseType::T(41)],
    },
    // 106 - While: "while" Condition BlockExpr;
    Production {
        lhs: 62,
        production: &[ParseType::N(4), ParseType::N(14), ParseType::T(42)],
    },
    // 107 - Tuple: "tuple";
    Production {
        lhs: 61,
        production: &[ParseType::T(43)],
    },
    // 108 - LocalVariable: LocalVariableOpt /* Option */ Identifier "=" Expr;
    Production {
        lhs: 52,
        production: &[
            ParseType::N(18),
            ParseType::T(44),
            ParseType::N(45),
            ParseType::N(53),
        ],
    },
    // 109 - LocalVariableOpt: StorageMode;
    Production {
        lhs: 53,
        production: &[ParseType::N(59)],
    },
    // 110 - LocalVariableOpt: ;
    Production {
        lhs: 53,
        production: &[],
    },
];

lazy_static! {
    static ref TOKENIZERS: Vec<(&'static str, Tokenizer)> = vec![(
        "INITIAL",
        Tokenizer::build(TERMINALS, SCANNER_0.0, SCANNER_0.1).unwrap()
    ),];
}

pub fn parse<'t, T>(
    input: &'t str,
    file_name: T,
    user_actions: &mut dyn UserActionsTrait<'t>,
) -> Result<Tree<ParseTreeType<'t>>>
where
    T: AsRef<Path>,
{
    let mut llk_parser = LLKParser::new(
        50,
        LOOKAHEAD_AUTOMATA,
        PRODUCTIONS,
        TERMINAL_NAMES,
        NON_TERMINALS,
    );
    let token_stream =
        RefCell::new(TokenStream::new(input, file_name, &TOKENIZERS, MAX_K).unwrap());
    let result = llk_parser.parse(token_stream, user_actions);
    match result {
        Ok(()) => Ok(llk_parser.parse_tree),
        Err(e) => Err(e),
    }
}
